package AcademicLeader;
//import acadleadclass.*;
import Classes.User;
import Classes.AcademicLeader;
import Classes.Lecturer;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class AcadLead_02Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form AcadLeadDashboard
     */
     private User currentUser;
     
    public AcadLead_02Dashboard(User currentUser) {
        initComponents();
        this.currentUser = currentUser;  
        loadDashboardData();
    }

    private void loadDashboardData() {
    setUserDetails();
    setStatistics();
    populateRecentModulesTable();
}

 private void setUserDetails() {

        lblUsername.setText(currentUser.getUsername());
        lblRole.setText(currentUser.getRole());

        List<AcademicLeader> leaders =
                AcademicLeader.loadLeaders("academicLeader.txt");

        for (AcademicLeader leader : leaders) {
            if (leader.getUsername().equals(currentUser.getUsername())) {
                lblName.setText(leader.getName());
                return;
            }
        }

        lblName.setText("Unknown");
    }

    
 private int countModules() {
        return Classes.Module.loadModules("module.txt").size();
    }
    
 private int countAcademicLeaders() {
        return AcademicLeader
                .loadLeaders("academicLeader.txt")
                .size();
    }
    
    private int countStudents() {

    List<User> users =
            User.loadUsers("user.txt");

    int count = 0;

    for (User u : users) {
        if (u.getRole().equalsIgnoreCase("Student")) {
            count++;
        }
    }

    return count;
}

 private int countAssignedLecturers() {

    String acadLeadID = null;

    List<AcademicLeader> leaders =
            AcademicLeader.loadLeaders("academicLeader.txt");

    for (AcademicLeader leader : leaders) {
        if (leader.getUsername()
                .equals(currentUser.getUsername())) {

            acadLeadID = leader.getAcadLeadID();
            break;
        }
    }

    if (acadLeadID == null) return 0;

    List<Lecturer> lecturers =
            Lecturer.loadLecturers("lecturer.txt");

    int count = 0;

    for (Lecturer lec : lecturers) {
        if (lec.getAcadLeadID().equals(acadLeadID)) {
            count++;
        }
    }

    return count;   }
 
 private void setStatistics() {

    lblCountMod.setText(String.valueOf(countModules()));
    lblCountAcad.setText(String.valueOf(countAcademicLeaders()));
    lblCountStud.setText(String.valueOf(countStudents()));
    lblCountLec.setText(String.valueOf(countAssignedLecturers()));
}
 
 private void populateRecentModulesTable() {

 List<Classes.Module> modules =
            Classes.Module.loadModules("module.txt");

        DefaultTableModel model = new DefaultTableModel();

        model.setColumnIdentifiers(new Object[]{
                "Module ID", "Module Name", "Credit Hour"
        });

        int start = Math.max(modules.size() - 5, 0);

        for (int i = start; i < modules.size(); i++) {

            Classes.Module m = modules.get(i);

            model.addRow(new Object[]{
                    m.getModuleID(),
                    m.getName(),
                    m.getCreditHour()
            });
        }

        tblMod.setModel(model);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblSumMod = new javax.swing.JLabel();
        lblSumAcad = new javax.swing.JLabel();
        lblSumStud = new javax.swing.JLabel();
        lblCountMod = new javax.swing.JLabel();
        lblCountLec = new javax.swing.JLabel();
        lblSumLec = new javax.swing.JLabel();
        lblCountStud = new javax.swing.JLabel();
        lblCountAcad = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMod = new javax.swing.JTable();
        lblWelcome = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(775, 643));

        jLabel1.setFont(new java.awt.Font("Helvetica World", 1, 36)); // NOI18N
        jLabel1.setText("Dashboard");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/IconUser.png"))); // NOI18N
        jButton1.setBorder(null);

        lblUsername.setText("username");

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblRole.setText("role");

        lblSumMod.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSumMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSumMod.setText("Total Modules:");
        lblSumMod.setAlignmentX(4.0F);
        lblSumMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 150, 150), 2, true));
        lblSumMod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSumAcad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSumAcad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSumAcad.setText("Total Academic Leaders:");
        lblSumAcad.setAlignmentX(4.0F);
        lblSumAcad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 150, 150), 2, true));
        lblSumAcad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSumStud.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSumStud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSumStud.setText("Total Students:");
        lblSumStud.setAlignmentX(4.0F);
        lblSumStud.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 150, 150), 2, true));
        lblSumStud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCountMod.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCountMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountMod.setText("00");
        lblCountMod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 150, 150), 2, true));
        lblCountMod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCountLec.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCountLec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountLec.setText("00");
        lblCountLec.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 150, 150), 2, true));
        lblCountLec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSumLec.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSumLec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSumLec.setText("Total Assigned Lecturers:");
        lblSumLec.setAlignmentX(4.0F);
        lblSumLec.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 150, 150), 2, true));
        lblSumLec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCountStud.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCountStud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountStud.setText("00");
        lblCountStud.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 150, 150), 2, true));
        lblCountStud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCountAcad.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCountAcad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountAcad.setText("00");
        lblCountAcad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 150, 150), 2, true));
        lblCountAcad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLayeredPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 150, 150), 2, true));

        jLabel5.setFont(new java.awt.Font("Helvetica World", 1, 24)); // NOI18N
        jLabel5.setText("Recently Added Modules");

        tblMod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMod);

        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lblWelcome.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblWelcome.setText("Welcome,");

        lblName.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblName.setForeground(new java.awt.Color(139, 82, 125));
        lblName.setText("XX XXXX XXXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(408, 408, 408)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblRole)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWelcome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblName))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSumLec, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblCountLec, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblSumAcad, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(lblCountAcad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSumMod, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblCountMod, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)
                                    .addComponent(lblSumStud, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblCountStud, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLayeredPane1)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRole)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(lblName))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSumMod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSumStud, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountMod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountStud, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSumAcad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountLec, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSumLec, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountAcad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCountAcad;
    private javax.swing.JLabel lblCountLec;
    private javax.swing.JLabel lblCountMod;
    private javax.swing.JLabel lblCountStud;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSumAcad;
    private javax.swing.JLabel lblSumLec;
    private javax.swing.JLabel lblSumMod;
    private javax.swing.JLabel lblSumStud;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblMod;
    // End of variables declaration//GEN-END:variables
}
