package AcademicLeader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lenovo
 */

import Classes.AcademicLeader;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import Classes.User;
public class AcadLead_06ProfileMain extends javax.swing.JPanel {
    
    private String loggedInUsername; //creyet user
    private User currentUser;
    private AcademicLeader currentLeader;

    private List<User> users;
    private List<AcademicLeader> leaders;

    CardLayout cardLayout;

    public AcadLead_06ProfileMain(User user) {
        initComponents();
        this.currentUser = user;
        this.loggedInUsername = currentUser.getUsername();

        lblProfileUsername.setText(currentUser.getUsername());
        lblProfileRole.setText(currentUser.getRole());
    
        pnlCardsProfile.add(pnlProfile, "pnlProfile");
        pnlCardsProfile.add(pnlUpdate, "pnlUpdate");
        pnlCardsProfile.add(pnlPassword, "pnlPassword");
        cardLayout = (CardLayout)(pnlCardsProfile.getLayout());
        
        // Load objects using class methods
        users = User.loadUsers("user.txt");
        leaders = AcademicLeader.loadLeaders("academicLeader.txt");

        loadCurrentObjects();
        populateProfileLabels();
    }

    // loading...ze dta
 private void loadCurrentObjects() {

        for (User u : users) {
            if (u.getUsername().equals(loggedInUsername)) {
                currentUser = u;
                break;
            }
        }

        for (AcademicLeader a : leaders) {
            if (a.getUsername().equals(loggedInUsername)) {
                currentLeader = a;
                break;
            }
        }
    }

 private void populateProfileLabels() {

        if (currentLeader != null) {
            lblID.setText(currentLeader.getAcadLeadID());
            lblUsername.setText(currentLeader.getUsername());
            lblName.setText(currentLeader.getName());
            lblFaculty.setText(currentLeader.getFacultyInCharge());
            lblTitle.setText(currentLeader.getTitle());
            lblEmail.setText(currentLeader.getEmail());
            lblPhone.setText(currentLeader.getPhoneNumber());
            lblAcadQual.setText(currentLeader.getAcademicQualification());
        }

        if (currentUser != null) {
            lblPassword.setText(currentUser.getPassword());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCardsProfile = new javax.swing.JPanel();
        pnlProfile = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblFaculty = new javax.swing.JLabel();
        lblAcadQual = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblProfileUsername = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        lblProfileRole = new javax.swing.JLabel();
        pnlUpdate = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtFaculty = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAcadQual = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        pnlPassword = new javax.swing.JPanel();
        P_txtConfirmPassword = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        P_txtID = new javax.swing.JTextField();
        P_txtNewPassword = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        P_txtCurrentPassword = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setName("pnlCardsProfile"); // NOI18N
        setPreferredSize(new java.awt.Dimension(775, 643));

        pnlCardsProfile.setLayout(new java.awt.CardLayout());

        pnlProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnlProfile.setPreferredSize(new java.awt.Dimension(775, 643));

        jLabel5.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel5.setText("Title");

        jLabel6.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel6.setText("Faculty");

        jLabel7.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel7.setText("Academic Qualification");

        jLabel10.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel10.setText("Username");

        jLabel8.setFont(new java.awt.Font("Helvetica World", 1, 22)); // NOI18N
        jLabel8.setText("My Profile");

        jLabel11.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel11.setText("Password");

        jButton1.setBackground(new java.awt.Color(236, 217, 226));
        jButton1.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jButton1.setText("Update Profile");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel9.setFont(new java.awt.Font("Helvetica World", 1, 17)); // NOI18N
        jLabel9.setText("Login Details");

        jButton2.setBackground(new java.awt.Color(236, 217, 226));
        jButton2.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jButton2.setText("Change Password");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel1.setText("Academic Leader ID");

        jLabel2.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel4.setText("Phone Number");

        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhone.setToolTipText("");
        lblPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblID.setToolTipText("");
        lblID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setToolTipText("");
        lblEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setToolTipText("");
        lblName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setToolTipText("");
        lblTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        lblFaculty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFaculty.setToolTipText("");
        lblFaculty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        lblAcadQual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcadQual.setToolTipText("");
        lblAcadQual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setToolTipText("");
        lblUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setToolTipText("");
        lblPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(194, 194, 194), 1, true));

        lblProfileUsername.setText("username");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/IconUser.png"))); // NOI18N
        jButton7.setBorder(null);

        lblProfileRole.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblProfileRole.setText("role");

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProfileLayout.createSequentialGroup()
                                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlProfileLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProfileUsername)
                                    .addComponent(lblProfileRole)))))
                    .addComponent(jLabel9)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(lblAcadQual, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileLayout.createSequentialGroup()
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7)
                            .addGroup(pnlProfileLayout.createSequentialGroup()
                                .addComponent(lblProfileUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProfileRole)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAcadQual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pnlCardsProfile.add(pnlProfile, "card2");

        pnlUpdate.setBackground(new java.awt.Color(255, 255, 255));
        pnlUpdate.setPreferredSize(new java.awt.Dimension(775, 643));

        txtUsername.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Helvetica World", 1, 17)); // NOI18N
        jLabel12.setText("Update Profile");

        txtPhone.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        txtFaculty.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        txtTitle.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel13.setText("Academic Leader ID");

        txtID.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel14.setText("Email");

        txtEmail.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel15.setText("Username");

        jLabel16.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel16.setText("Academic Qualification");

        jLabel17.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel17.setText("Phone Number");

        txtAcadQual.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel18.setText("Name");

        jButton3.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel19.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel19.setText("Faculty");

        jButton4.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jButton4.setText("Confirm Update");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel20.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel20.setText("Title");

        jLabel21.setFont(new java.awt.Font("Helvetica World", 1, 22)); // NOI18N
        jLabel21.setText("My Profile");

        txtName.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlUpdateLayout = new javax.swing.GroupLayout(pnlUpdate);
        pnlUpdate.setLayout(pnlUpdateLayout);
        pnlUpdateLayout.setHorizontalGroup(
            pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel12)
                    .addGroup(pnlUpdateLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addGroup(pnlUpdateLayout.createSequentialGroup()
                                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(250, 250, 250)
                                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addGroup(pnlUpdateLayout.createSequentialGroup()
                                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlUpdateLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19)
                                            .addComponent(txtAcadQual, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16)))
                                    .addGroup(pnlUpdateLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4)
                                        .addGap(204, 204, 204)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUpdateLayout.setVerticalGroup(
            pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAcadQual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUpdateLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(30, 30, 30)
                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCardsProfile.add(pnlUpdate, "card3");

        pnlPassword.setBackground(new java.awt.Color(255, 255, 255));
        pnlPassword.setMaximumSize(new java.awt.Dimension(775, 643));
        pnlPassword.setMinimumSize(new java.awt.Dimension(775, 643));
        pnlPassword.setPreferredSize(new java.awt.Dimension(775, 643));

        P_txtConfirmPassword.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        P_txtConfirmPassword.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel22.setText("Current Password");

        P_txtID.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        P_txtNewPassword.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel23.setText("New Password");

        jLabel24.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel24.setText("Confirm New Password");

        jLabel25.setFont(new java.awt.Font("Helvetica World", 1, 17)); // NOI18N
        jLabel25.setText("Change Password");

        jLabel26.setFont(new java.awt.Font("Helvetica World", 1, 22)); // NOI18N
        jLabel26.setText("My Profile");

        P_txtCurrentPassword.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N

        jButton5.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jButton5.setText("Cancel");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jLabel27.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jLabel27.setText("Academic Leader ID");

        jButton6.setFont(new java.awt.Font("Helvetica World", 0, 12)); // NOI18N
        jButton6.setText("Confirm Change");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout pnlPasswordLayout = new javax.swing.GroupLayout(pnlPassword);
        pnlPassword.setLayout(pnlPasswordLayout);
        pnlPasswordLayout.setHorizontalGroup(
            pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasswordLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addGroup(pnlPasswordLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlPasswordLayout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6))
                            .addGroup(pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(P_txtCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)
                                .addComponent(P_txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(P_txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24)
                                .addComponent(P_txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPasswordLayout.setVerticalGroup(
            pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(20, 20, 20)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_txtCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(P_txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pnlCardsProfile.add(pnlPassword, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCardsProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCardsProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("pnlCardsProfile");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtID.setText(currentLeader.getAcadLeadID());
        txtEmail.setText(currentLeader.getEmail());
        txtUsername.setText(currentLeader.getUsername());
        txtName.setText(currentLeader.getName());
        txtTitle.setText(currentLeader.getTitle());
        txtPhone.setText(currentLeader.getPhoneNumber());
        txtFaculty.setText(currentLeader.getFacultyInCharge());
        txtAcadQual.setText(currentLeader.getAcademicQualification());
        cardLayout.show(pnlCardsProfile, "pnlUpdate");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        P_txtID.setText(currentLeader.getAcadLeadID());
        cardLayout.show(pnlCardsProfile, "pnlPassword");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCardsProfile, "pnlProfile");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String newUsername = txtUsername.getText().trim();
        String newName = txtName.getText().trim();
        String newEmail = txtEmail.getText().trim();
        String newPhone = txtPhone.getText().trim();
        String newTitle = txtTitle.getText().trim();
        String newFaculty = txtFaculty.getText().trim();
        String newAcadQual = txtAcadQual.getText().trim();

        // Update Leader object
        currentLeader.setUsername(newUsername);
        currentLeader.setName(newName);
        currentLeader.setEmail(newEmail);
        currentLeader.setPhoneNumber(newPhone);
        currentLeader.setTitle(newTitle);
        currentLeader.setFacultyInCharge(newFaculty);
        currentLeader.setAcademicQualification(newAcadQual);

        // Update User object username if changed
        if (!currentUser.getUsername().equals(newUsername)) {
            currentUser.setUsername(newUsername);
            loggedInUsername = newUsername;
        }

        // Save back to files
        AcademicLeader.saveLeaders("academicLeader.txt", leaders);
        User.saveUsers("user.txt", users);

        populateProfileLabels();

        JOptionPane.showMessageDialog(this, "Profile updated successfully!");
        cardLayout.show(pnlCardsProfile, "pnlProfile");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCardsProfile, "pnlProfile");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String currentPass = P_txtCurrentPassword.getText().trim();
        String newPass = P_txtNewPassword.getText().trim();
        String confirmPass = P_txtConfirmPassword.getText().trim();

        if (!currentUser.getPassword().equals(currentPass)) {
            JOptionPane.showMessageDialog(this, "Current password is incorrect!");
            return;
        }

        if (!newPass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(this, "New password and confirmation do not match!");
            return;
        }

        currentUser.setPassword(newPass);

        User.saveUsers("user.txt", users);

        lblPassword.setText(newPass);

        JOptionPane.showMessageDialog(this, "Password updated successfully!");
        cardLayout.show(pnlCardsProfile, "pnlProfile");
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P_txtConfirmPassword;
    private javax.swing.JTextField P_txtCurrentPassword;
    private javax.swing.JTextField P_txtID;
    private javax.swing.JTextField P_txtNewPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAcadQual;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaculty;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblProfileRole;
    private javax.swing.JLabel lblProfileUsername;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlCardsProfile;
    private javax.swing.JPanel pnlPassword;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlUpdate;
    private javax.swing.JTextField txtAcadQual;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaculty;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
