package Student;

import Classes.AssessmentData;
import Classes.ResultData;
import Classes.ClassData;
import Classes.RegisteredClassData;
import Classes.ClassInfo;
import Classes.RegisteredClass;
import Classes.Assessment;
import Classes.Result;
import Classes.Session;
import Login.AFS_LoginPage;

// java packages
import javax.swing.*;
import java.util.*;


public class StudentAssessments extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentAssessments.class.getName());
    
    // data
    private final Map<String, ClassInfo> classById = new HashMap<>();
    private final List<String> registeredClassIds = new ArrayList<>();
    private final Map<String, List<AssessmentRow>> assessmentsByClass = new HashMap<>();
    private final Map<String, ResultRow> resultByStudentAssess = new HashMap<>();

    /**
     * Creates new form StudentAssessments
     */
    public StudentAssessments() {
        initComponents();
        initCustom();
        
        setSize(1031, 643); 
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        loadHeaderFromSession();     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbBase = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        gap1 = new javax.swing.JPanel();
        pnlAFSlogo = new javax.swing.JPanel();
        lblAFSlogo = new javax.swing.JLabel();
        gap2 = new javax.swing.JPanel();
        pnlNavDashboard = new javax.swing.JPanel();
        btnNavDashboard = new javax.swing.JButton();
        pnlNavMyClasses = new javax.swing.JPanel();
        btnNavMyClasses = new javax.swing.JButton();
        pnlNavAssessments = new javax.swing.JPanel();
        btnNavAssessments = new javax.swing.JButton();
        pnlNavGrades = new javax.swing.JPanel();
        btnNavGrades = new javax.swing.JButton();
        pnlNavFeedback = new javax.swing.JPanel();
        btnNavFeedback = new javax.swing.JButton();
        pnlNavProfile = new javax.swing.JPanel();
        btnNavProfile = new javax.swing.JButton();
        pnlNavLogout = new javax.swing.JPanel();
        btnNavLogout = new javax.swing.JButton();
        gap3 = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        topTitle = new javax.swing.JPanel();
        txtRegisterNewClasses = new javax.swing.JLabel();
        topUserInfo = new javax.swing.JPanel();
        StudentProfilePic = new javax.swing.JLabel();
        StudentRole = new javax.swing.JLabel();
        StudentID = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        lblFilterAss = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        cbClass = new javax.swing.JComboBox<>();
        lblAssessment = new javax.swing.JLabel();
        cbAssessment = new javax.swing.JComboBox<>();
        lblAssessmentDetails = new javax.swing.JLabel();
        pnlDetailsCard = new javax.swing.JPanel();
        lblAssDetailClass = new javax.swing.JLabel();
        lblAssDetailClassResult = new javax.swing.JLabel();
        lblAssDetailsAssType = new javax.swing.JLabel();
        lblAssDetailAssTypeResult = new javax.swing.JLabel();
        lblAssDetailsFullMark = new javax.swing.JLabel();
        lblAssDetailFullMarkResult = new javax.swing.JLabel();
        lblAssDetailsWeightage = new javax.swing.JLabel();
        lblAssDetailWeightageResult = new javax.swing.JLabel();
        lblResults = new javax.swing.JLabel();
        pnlResultsCard = new javax.swing.JPanel();
        lblResultsMarkReceived = new javax.swing.JLabel();
        lblResultsMarkRecResult = new javax.swing.JLabel();
        lblResultsResStat = new javax.swing.JLabel();
        lblResultsResStatResult = new javax.swing.JLabel();
        pnlFeedbackCard = new javax.swing.JPanel();
        spLectAssFeedback = new javax.swing.JScrollPane();
        taLectAssFeedback = new javax.swing.JTextArea();
        lblFeedback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Assessments");
        setResizable(false);

        dbBase.setBackground(new java.awt.Color(255, 255, 255));
        dbBase.setLayout(new java.awt.BorderLayout());

        sidebar.setBackground(new java.awt.Color(24, 29, 49));
        sidebar.setPreferredSize(new java.awt.Dimension(209, 643));
        sidebar.setLayout(new javax.swing.BoxLayout(sidebar, javax.swing.BoxLayout.Y_AXIS));

        gap1.setBackground(new java.awt.Color(24, 29, 49));
        gap1.setPreferredSize(new java.awt.Dimension(209, 43));

        javax.swing.GroupLayout gap1Layout = new javax.swing.GroupLayout(gap1);
        gap1.setLayout(gap1Layout);
        gap1Layout.setHorizontalGroup(
            gap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        gap1Layout.setVerticalGroup(
            gap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        sidebar.add(gap1);

        pnlAFSlogo.setBackground(new java.awt.Color(24, 29, 49));

        lblAFSlogo.setBackground(new java.awt.Color(24, 29, 49));
        lblAFSlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AFS Logo.png"))); // NOI18N
        lblAFSlogo.setText("jLabel1");

        javax.swing.GroupLayout pnlAFSlogoLayout = new javax.swing.GroupLayout(pnlAFSlogo);
        pnlAFSlogo.setLayout(pnlAFSlogoLayout);
        pnlAFSlogoLayout.setHorizontalGroup(
            pnlAFSlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAFSlogoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAFSlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlAFSlogoLayout.setVerticalGroup(
            pnlAFSlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAFSlogoLayout.createSequentialGroup()
                .addComponent(lblAFSlogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(pnlAFSlogo);

        gap2.setBackground(new java.awt.Color(24, 29, 49));
        gap2.setPreferredSize(new java.awt.Dimension(209, 43));

        javax.swing.GroupLayout gap2Layout = new javax.swing.GroupLayout(gap2);
        gap2.setLayout(gap2Layout);
        gap2Layout.setHorizontalGroup(
            gap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        gap2Layout.setVerticalGroup(
            gap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        sidebar.add(gap2);

        pnlNavDashboard.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavDashboard.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavDashboard.setBackground(new java.awt.Color(24, 29, 49));
        btnNavDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnNavDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconDb.png"))); // NOI18N
        btnNavDashboard.setText("   Dashboard");
        btnNavDashboard.setBorder(null);
        btnNavDashboard.setBorderPainted(false);
        btnNavDashboard.setContentAreaFilled(false);
        btnNavDashboard.setFocusPainted(false);
        btnNavDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavDashboard.setPreferredSize(new java.awt.Dimension(92, 40));
        btnNavDashboard.setVerifyInputWhenFocusTarget(false);
        btnNavDashboard.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNavDashboard.addActionListener(this::btnNavDashboardActionPerformed);

        javax.swing.GroupLayout pnlNavDashboardLayout = new javax.swing.GroupLayout(pnlNavDashboard);
        pnlNavDashboard.setLayout(pnlNavDashboardLayout);
        pnlNavDashboardLayout.setHorizontalGroup(
            pnlNavDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavDashboardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnNavDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlNavDashboardLayout.setVerticalGroup(
            pnlNavDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNavDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidebar.add(pnlNavDashboard);

        pnlNavMyClasses.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavMyClasses.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavMyClasses.setBackground(new java.awt.Color(24, 29, 49));
        btnNavMyClasses.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavMyClasses.setForeground(new java.awt.Color(255, 255, 255));
        btnNavMyClasses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconClass.png"))); // NOI18N
        btnNavMyClasses.setText("   My Classes");
        btnNavMyClasses.setBorder(null);
        btnNavMyClasses.setBorderPainted(false);
        btnNavMyClasses.setContentAreaFilled(false);
        btnNavMyClasses.setFocusPainted(false);
        btnNavMyClasses.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavMyClasses.addActionListener(this::btnNavMyClassesActionPerformed);

        javax.swing.GroupLayout pnlNavMyClassesLayout = new javax.swing.GroupLayout(pnlNavMyClasses);
        pnlNavMyClasses.setLayout(pnlNavMyClassesLayout);
        pnlNavMyClassesLayout.setHorizontalGroup(
            pnlNavMyClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavMyClassesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNavMyClasses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavMyClassesLayout.setVerticalGroup(
            pnlNavMyClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavMyClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNavMyClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavMyClasses);

        pnlNavAssessments.setBackground(new java.awt.Color(20, 24, 49));
        pnlNavAssessments.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavAssessments.setBackground(new java.awt.Color(24, 29, 49));
        btnNavAssessments.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavAssessments.setForeground(new java.awt.Color(166, 199, 155));
        btnNavAssessments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ClickAss.png"))); // NOI18N
        btnNavAssessments.setText("  Assessments");
        btnNavAssessments.setBorder(null);
        btnNavAssessments.setBorderPainted(false);
        btnNavAssessments.setContentAreaFilled(false);
        btnNavAssessments.setFocusPainted(false);
        btnNavAssessments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavAssessments.addActionListener(this::btnNavAssessmentsActionPerformed);

        javax.swing.GroupLayout pnlNavAssessmentsLayout = new javax.swing.GroupLayout(pnlNavAssessments);
        pnlNavAssessments.setLayout(pnlNavAssessmentsLayout);
        pnlNavAssessmentsLayout.setHorizontalGroup(
            pnlNavAssessmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavAssessmentsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNavAssessments, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlNavAssessmentsLayout.setVerticalGroup(
            pnlNavAssessmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavAssessmentsLayout.createSequentialGroup()
                .addComponent(btnNavAssessments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavAssessments);

        pnlNavGrades.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavGrades.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavGrades.setBackground(new java.awt.Color(24, 29, 49));
        btnNavGrades.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavGrades.setForeground(new java.awt.Color(255, 255, 255));
        btnNavGrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconGrading.png"))); // NOI18N
        btnNavGrades.setText("   Grades");
        btnNavGrades.setBorder(null);
        btnNavGrades.setBorderPainted(false);
        btnNavGrades.setContentAreaFilled(false);
        btnNavGrades.setFocusPainted(false);
        btnNavGrades.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavGrades.addActionListener(this::btnNavGradesActionPerformed);

        javax.swing.GroupLayout pnlNavGradesLayout = new javax.swing.GroupLayout(pnlNavGrades);
        pnlNavGrades.setLayout(pnlNavGradesLayout);
        pnlNavGradesLayout.setHorizontalGroup(
            pnlNavGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavGradesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnNavGrades)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavGradesLayout.setVerticalGroup(
            pnlNavGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavGradesLayout.createSequentialGroup()
                .addComponent(btnNavGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavGrades);

        pnlNavFeedback.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavFeedback.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavFeedback.setBackground(new java.awt.Color(24, 29, 49));
        btnNavFeedback.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnNavFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconFeedback.png"))); // NOI18N
        btnNavFeedback.setText("   Feedback");
        btnNavFeedback.setBorder(null);
        btnNavFeedback.setBorderPainted(false);
        btnNavFeedback.setContentAreaFilled(false);
        btnNavFeedback.setFocusPainted(false);
        btnNavFeedback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavFeedback.addActionListener(this::btnNavFeedbackActionPerformed);

        javax.swing.GroupLayout pnlNavFeedbackLayout = new javax.swing.GroupLayout(pnlNavFeedback);
        pnlNavFeedback.setLayout(pnlNavFeedbackLayout);
        pnlNavFeedbackLayout.setHorizontalGroup(
            pnlNavFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavFeedbackLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNavFeedback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavFeedbackLayout.setVerticalGroup(
            pnlNavFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavFeedbackLayout.createSequentialGroup()
                .addComponent(btnNavFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavFeedback);

        pnlNavProfile.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavProfile.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavProfile.setBackground(new java.awt.Color(24, 29, 49));
        btnNavProfile.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnNavProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconProfile.png"))); // NOI18N
        btnNavProfile.setText("   Profile");
        btnNavProfile.setBorder(null);
        btnNavProfile.setBorderPainted(false);
        btnNavProfile.setContentAreaFilled(false);
        btnNavProfile.setFocusPainted(false);
        btnNavProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavProfile.addActionListener(this::btnNavProfileActionPerformed);

        javax.swing.GroupLayout pnlNavProfileLayout = new javax.swing.GroupLayout(pnlNavProfile);
        pnlNavProfile.setLayout(pnlNavProfileLayout);
        pnlNavProfileLayout.setHorizontalGroup(
            pnlNavProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavProfileLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNavProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavProfileLayout.setVerticalGroup(
            pnlNavProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavProfileLayout.createSequentialGroup()
                .addComponent(btnNavProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavProfile);

        pnlNavLogout.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavLogout.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavLogout.setBackground(new java.awt.Color(24, 29, 49));
        btnNavLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnNavLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconLogout.png"))); // NOI18N
        btnNavLogout.setText("   Logout");
        btnNavLogout.setAutoscrolls(true);
        btnNavLogout.setBorder(null);
        btnNavLogout.setBorderPainted(false);
        btnNavLogout.setContentAreaFilled(false);
        btnNavLogout.setFocusPainted(false);
        btnNavLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavLogout.addActionListener(this::btnNavLogoutActionPerformed);

        javax.swing.GroupLayout pnlNavLogoutLayout = new javax.swing.GroupLayout(pnlNavLogout);
        pnlNavLogout.setLayout(pnlNavLogoutLayout);
        pnlNavLogoutLayout.setHorizontalGroup(
            pnlNavLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLogoutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNavLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavLogoutLayout.setVerticalGroup(
            pnlNavLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavLogoutLayout.createSequentialGroup()
                .addComponent(btnNavLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavLogout);

        gap3.setBackground(new java.awt.Color(24, 29, 49));
        gap3.setPreferredSize(new java.awt.Dimension(209, 800));

        javax.swing.GroupLayout gap3Layout = new javax.swing.GroupLayout(gap3);
        gap3.setLayout(gap3Layout);
        gap3Layout.setHorizontalGroup(
            gap3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        gap3Layout.setVerticalGroup(
            gap3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        sidebar.add(gap3);

        dbBase.add(sidebar, java.awt.BorderLayout.WEST);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new java.awt.BorderLayout());

        top.setBackground(new java.awt.Color(255, 255, 255));
        top.setPreferredSize(new java.awt.Dimension(822, 80));
        top.setLayout(new java.awt.BorderLayout());

        topTitle.setBackground(new java.awt.Color(255, 255, 255));
        topTitle.setPreferredSize(new java.awt.Dimension(100, 80));

        txtRegisterNewClasses.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        txtRegisterNewClasses.setText("Assessments");

        javax.swing.GroupLayout topTitleLayout = new javax.swing.GroupLayout(topTitle);
        topTitle.setLayout(topTitleLayout);
        topTitleLayout.setHorizontalGroup(
            topTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topTitleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtRegisterNewClasses)
                .addContainerGap(505, Short.MAX_VALUE))
        );
        topTitleLayout.setVerticalGroup(
            topTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topTitleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtRegisterNewClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        top.add(topTitle, java.awt.BorderLayout.CENTER);

        topUserInfo.setBackground(new java.awt.Color(255, 255, 255));
        topUserInfo.setPreferredSize(new java.awt.Dimension(150, 80));

        StudentProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User Icon.png"))); // NOI18N
        StudentProfilePic.setText("jLabel2");

        StudentRole.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        StudentRole.setText("Student");

        StudentID.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        StudentID.setText("TPXXXXXX");

        javax.swing.GroupLayout topUserInfoLayout = new javax.swing.GroupLayout(topUserInfo);
        topUserInfo.setLayout(topUserInfoLayout);
        topUserInfoLayout.setHorizontalGroup(
            topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addGroup(topUserInfoLayout.createSequentialGroup()
                        .addComponent(StudentRole, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        topUserInfoLayout.setVerticalGroup(
            topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topUserInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topUserInfoLayout.createSequentialGroup()
                        .addComponent(StudentID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StudentRole)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        top.add(topUserInfo, java.awt.BorderLayout.EAST);

        main.add(top, java.awt.BorderLayout.NORTH);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(822, 563));

        lblFilterAss.setBackground(new java.awt.Color(255, 255, 255));
        lblFilterAss.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblFilterAss.setText("Filter");
        lblFilterAss.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblClass.setBackground(new java.awt.Color(255, 255, 255));
        lblClass.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblClass.setText("Class:");
        lblClass.setPreferredSize(new java.awt.Dimension(90, 24));

        cbClass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Class --" }));
        cbClass.addActionListener(this::cbClassActionPerformed);

        lblAssessment.setBackground(new java.awt.Color(255, 255, 255));
        lblAssessment.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblAssessment.setText("Assessment:");
        lblAssessment.setPreferredSize(new java.awt.Dimension(90, 24));

        cbAssessment.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbAssessment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Assessment --" }));
        cbAssessment.addActionListener(this::cbAssessmentActionPerformed);

        lblAssessmentDetails.setBackground(new java.awt.Color(255, 255, 255));
        lblAssessmentDetails.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblAssessmentDetails.setText("Assessment Details");
        lblAssessmentDetails.setPreferredSize(new java.awt.Dimension(90, 24));

        pnlDetailsCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetailsCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlDetailsCard.setPreferredSize(new java.awt.Dimension(400, 330));
        pnlDetailsCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAssDetailClass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAssDetailClass.setText("Class:");
        pnlDetailsCard.add(lblAssDetailClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 140, 20));

        lblAssDetailClassResult.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAssDetailClassResult.setText("-");
        pnlDetailsCard.add(lblAssDetailClassResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 35, 180, 20));

        lblAssDetailsAssType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAssDetailsAssType.setText("Assessment Type:");
        pnlDetailsCard.add(lblAssDetailsAssType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, 140, 20));

        lblAssDetailAssTypeResult.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAssDetailAssTypeResult.setText("-");
        pnlDetailsCard.add(lblAssDetailAssTypeResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 115, 180, 20));

        lblAssDetailsFullMark.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAssDetailsFullMark.setText("Full Mark:");
        pnlDetailsCard.add(lblAssDetailsFullMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 195, 140, 20));

        lblAssDetailFullMarkResult.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAssDetailFullMarkResult.setText("-");
        pnlDetailsCard.add(lblAssDetailFullMarkResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 195, 180, 20));

        lblAssDetailsWeightage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAssDetailsWeightage.setText("Weightage");
        pnlDetailsCard.add(lblAssDetailsWeightage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 275, 140, 20));

        lblAssDetailWeightageResult.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAssDetailWeightageResult.setText("-");
        pnlDetailsCard.add(lblAssDetailWeightageResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 275, 180, 20));

        lblResults.setBackground(new java.awt.Color(255, 255, 255));
        lblResults.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblResults.setText("Feedback");
        lblResults.setPreferredSize(new java.awt.Dimension(90, 24));

        pnlResultsCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlResultsCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlResultsCard.setPreferredSize(new java.awt.Dimension(400, 330));
        pnlResultsCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResultsMarkReceived.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblResultsMarkReceived.setText("Mark Received:");
        pnlResultsCard.add(lblResultsMarkReceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 20));

        lblResultsMarkRecResult.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblResultsMarkRecResult.setText("-");
        pnlResultsCard.add(lblResultsMarkRecResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, 20));

        lblResultsResStat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblResultsResStat.setText("Results Status:");
        pnlResultsCard.add(lblResultsResStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, 110, 20));

        lblResultsResStatResult.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblResultsResStatResult.setText("-");
        pnlResultsCard.add(lblResultsResStatResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 75, 110, 20));

        pnlFeedbackCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlFeedbackCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFeedbackCard.setPreferredSize(new java.awt.Dimension(400, 330));
        pnlFeedbackCard.setLayout(new java.awt.BorderLayout());

        taLectAssFeedback.setEditable(false);
        taLectAssFeedback.setBackground(new java.awt.Color(255, 255, 255));
        taLectAssFeedback.setColumns(20);
        taLectAssFeedback.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        taLectAssFeedback.setLineWrap(true);
        taLectAssFeedback.setRows(5);
        taLectAssFeedback.setWrapStyleWord(true);
        taLectAssFeedback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spLectAssFeedback.setViewportView(taLectAssFeedback);

        pnlFeedbackCard.add(spLectAssFeedback, java.awt.BorderLayout.CENTER);

        lblFeedback.setBackground(new java.awt.Color(255, 255, 255));
        lblFeedback.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblFeedback.setText("Results");
        lblFeedback.setPreferredSize(new java.awt.Dimension(90, 24));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDetailsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAssessmentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlResultsCard, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                            .addComponent(pnlFeedbackCard, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFilterAss, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblFilterAss, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAssessment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssessmentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDetailsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(pnlResultsCard, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlFeedbackCard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        main.add(content, java.awt.BorderLayout.LINE_END);

        dbBase.add(main, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadHeaderFromSession() {
        String sid = Session.getStudentId();
        sid = (sid == null) ? "" : sid.trim();

        StudentID.setText(!sid.isBlank() ? sid : "TPXXXXXX");
        StudentRole.setText("Student");
    }
    
    private static class AssessmentRow {
        String assessId, classId, assessType;
        double fullMark;
        double weightage;
        AssessmentRow(String assessId, String classId, String assessType, double fullMark, double weightage) {
            this.assessId = assessId;
            this.classId = classId;
            this.assessType = assessType;
            this.fullMark = fullMark;
            this.weightage = weightage;
        }
    }
    
    private static class ResultRow {
        String resultId, studentId, assessId;
        Double markReceived;   // null = not released
        String feedback;
        ResultRow(String resultId, String studentId, String assessId, Double markReceived, String feedback) {
            this.resultId = resultId;
            this.studentId = studentId;
            this.assessId = assessId;
            this.markReceived = markReceived;
            this.feedback = feedback;
        }
    }
    
    private void initCustom() {
        cbClass.removeAllItems();
        cbClass.addItem("-- Select Class --");

        cbAssessment.removeAllItems();
        cbAssessment.addItem("-- Select Assessment --");

        clearDisplay();

        // load data from files
        loadClasses();
        loadRegisteredClassesForCurrentStudent();
        loadAssessments();
        loadResults();

        // only choose registered classes
        populateClassCombo();
    }

    private void loadClasses() {
        classById.clear();
        List<ClassInfo> classes = new ClassData().readAll();
        for (ClassInfo c : classes) {
            classById.put(c.getClassID(), c);
        }
    }
    
    private void loadRegisteredClassesForCurrentStudent() {
        registeredClassIds.clear();

        String studentId = Session.getStudentId();
        if (studentId == null || studentId.isBlank()) return;

        List<RegisteredClass> regs = new RegisteredClassData().findByStudentId(studentId);
        for (RegisteredClass rc : regs) {
            registeredClassIds.add(rc.getClassID());
        }

        Collections.sort(registeredClassIds);
    }
    
    private void loadAssessments() {
        assessmentsByClass.clear();

        AssessmentData ad = new AssessmentData();

        for (String classId : registeredClassIds) {
            List<Assessment> list = ad.findByClassId(classId);

            for (Assessment a : list) {
                AssessmentRow row = new AssessmentRow(
                    a.getAssessID(),
                    a.getClassID(),
                    a.getAssessType(),
                    (double) a.getFullMark(),
                    a.getWeightage()
                );

                assessmentsByClass
                    .computeIfAbsent(classId, k -> new ArrayList<>())
                    .add(row);
            }
        }

        for (List<AssessmentRow> list : assessmentsByClass.values()) {
            list.sort(Comparator.comparing(x -> x.assessId));
        }
    }
    
    private void loadResults() {
        resultByStudentAssess.clear();

        String studentId = Session.getStudentId();
        if (studentId == null || studentId.isBlank()) return;

        ResultData rd = new ResultData();
        List<Result> results = rd.findByStudentId(studentId);

        for (Result r : results) {
            ResultRow rr = new ResultRow(
                r.getResultID(),
                r.getStudentID(),
                r.getAssessID(),
                r.getMarkReceived(),
                r.getFeedback()
            );

            resultByStudentAssess.put(key(r.getStudentID(), r.getAssessID()), rr);
        }
    }
    
    private void populateClassCombo() {
        // keep first item
        for (String classId : registeredClassIds) {
            ClassInfo c = classById.get(classId);
            String display = (c == null) ? classId : (classId + " - " + c.getName());
            cbClass.addItem(display);
        }

        if (registeredClassIds.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No registered classes found.\nPlease register a class first.");
        }
    }
    
    private void btnNavDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavDashboardActionPerformed
        new StudentDashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavDashboardActionPerformed

    private void btnNavMyClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavMyClassesActionPerformed
        new StudentMyClasses().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavMyClassesActionPerformed

    private void btnNavAssessmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavAssessmentsActionPerformed
        //
    }//GEN-LAST:event_btnNavAssessmentsActionPerformed

    private void btnNavGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavGradesActionPerformed
        new StudentGrades().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavGradesActionPerformed

    private void btnNavFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavFeedbackActionPerformed
        new StudentFeedback().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavFeedbackActionPerformed

    private void btnNavProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavProfileActionPerformed
        new StudentProfile().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavProfileActionPerformed

    private void cbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClassActionPerformed
        onClassChanged();
    }//GEN-LAST:event_cbClassActionPerformed

    private void cbAssessmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAssessmentActionPerformed
        onAssessmentChanged();
    }//GEN-LAST:event_cbAssessmentActionPerformed

    private void btnNavLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavLogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
                "Logging out?", 
                "Confirmation", 
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new AFS_LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnNavLogoutActionPerformed
    
    private void onClassChanged() {
        clearDisplay();

        String classId = getSelectedClassId();
        if (classId == null) {
            cbAssessment.removeAllItems();
            cbAssessment.addItem("-- Select Assessment --");
            return;
        }

        lblAssDetailClassResult.setText(classId);

        cbAssessment.setEnabled(true);
        cbAssessment.removeAllItems();
        cbAssessment.addItem("-- Select Assessment --");

        List<AssessmentRow> list = assessmentsByClass.getOrDefault(classId, Collections.emptyList());
        for (AssessmentRow a : list) {
            cbAssessment.addItem(a.assessId + " - " + a.assessType);
        }

        if (list.isEmpty()) {
            taLectAssFeedback.setText("No assessments found for this class.");
        }
    }
    
    private void onAssessmentChanged() {
        String classId = getSelectedClassId();
        String assessId = getSelectedAssessId();

        if (classId == null || assessId == null) return;

        // find assessment row
        AssessmentRow chosen = null;
        for (AssessmentRow a : assessmentsByClass.getOrDefault(classId, Collections.emptyList())) {
            if (a.assessId.equalsIgnoreCase(assessId)) {
                chosen = a;
                break;
            }
        }
        if (chosen == null) return;

        // details panel
        lblAssDetailClassResult.setText(chosen.classId);
        lblAssDetailAssTypeResult.setText(chosen.assessType);
        lblAssDetailFullMarkResult.setText(String.valueOf(chosen.fullMark));
        lblAssDetailWeightageResult.setText(formatWeightage(chosen.weightage));

        // result & feedback
        String studentId = Session.getStudentId();
        ResultRow rr = (studentId == null) ? null : resultByStudentAssess.get(key(studentId, chosen.assessId));

        if (rr == null || rr.markReceived == null) {
            lblResultsMarkRecResult.setText("— / " + chosen.fullMark);
            lblResultsResStatResult.setText("Pending");
            taLectAssFeedback.setText("No feedback available.");
        } else {
            lblResultsMarkRecResult.setText(fmtMark(rr.markReceived) + " / " + chosen.fullMark);
            lblResultsResStatResult.setText("Released");
            taLectAssFeedback.setText(rr.feedback == null || rr.feedback.isBlank() ? "No feedback available." : rr.feedback);
        }
    }
    
    private static String fmtMark(Double v) {
        if (v == null) return "—";
        if (Math.abs(v - Math.round(v)) < 0.0000001) return String.valueOf((long)Math.round(v));
        return String.valueOf(v);
    }
    
    private void clearDisplay() {
        lblAssDetailClassResult.setText("—");
        lblAssDetailAssTypeResult.setText("—");
        lblAssDetailFullMarkResult.setText("—");
        lblAssDetailWeightageResult.setText("—");
        lblResultsMarkRecResult.setText("—");
        lblResultsResStatResult.setText("—");   
        taLectAssFeedback.setText("");
        if (cbAssessment.getItemCount() > 0) cbAssessment.setSelectedIndex(0);
    }
    
    private String getSelectedClassId() {
        Object sel = cbClass.getSelectedItem();
        if (sel == null) return null;
        String s = sel.toString();
        if (s.startsWith("--")) return null;

        int idx = s.indexOf(" - ");
        return idx >= 0 ? s.substring(0, idx).trim() : s.trim();
    }

    private String getSelectedAssessId() {
        Object sel = cbAssessment.getSelectedItem();
        if (sel == null) return null;
        String s = sel.toString();
        if (s.startsWith("--")) return null;

        int idx = s.indexOf(" - ");
        return idx >= 0 ? s.substring(0, idx).trim() : s.trim();
    }

    private static String key(String studentId, String assessId) {
        return studentId + "|" + assessId;
    }

    private static String formatWeightage(double w) {
        double pct = w * 100.0;
        if (Math.abs(pct - Math.round(pct)) < 0.00001) return ((int) Math.round(pct)) + "%";
        return String.format(Locale.US, "%.1f%%", pct);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StudentID;
    private javax.swing.JLabel StudentProfilePic;
    private javax.swing.JLabel StudentRole;
    private javax.swing.JButton btnNavAssessments;
    private javax.swing.JButton btnNavDashboard;
    private javax.swing.JButton btnNavFeedback;
    private javax.swing.JButton btnNavGrades;
    private javax.swing.JButton btnNavLogout;
    private javax.swing.JButton btnNavMyClasses;
    private javax.swing.JButton btnNavProfile;
    private javax.swing.JComboBox<String> cbAssessment;
    private javax.swing.JComboBox<String> cbClass;
    private javax.swing.JPanel content;
    private javax.swing.JPanel dbBase;
    private javax.swing.JPanel gap1;
    private javax.swing.JPanel gap2;
    private javax.swing.JPanel gap3;
    private javax.swing.JLabel lblAFSlogo;
    private javax.swing.JLabel lblAssDetailAssTypeResult;
    private javax.swing.JLabel lblAssDetailClass;
    private javax.swing.JLabel lblAssDetailClassResult;
    private javax.swing.JLabel lblAssDetailFullMarkResult;
    private javax.swing.JLabel lblAssDetailWeightageResult;
    private javax.swing.JLabel lblAssDetailsAssType;
    private javax.swing.JLabel lblAssDetailsFullMark;
    private javax.swing.JLabel lblAssDetailsWeightage;
    private javax.swing.JLabel lblAssessment;
    private javax.swing.JLabel lblAssessmentDetails;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblFilterAss;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblResultsMarkRecResult;
    private javax.swing.JLabel lblResultsMarkReceived;
    private javax.swing.JLabel lblResultsResStat;
    private javax.swing.JLabel lblResultsResStatResult;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnlAFSlogo;
    private javax.swing.JPanel pnlDetailsCard;
    private javax.swing.JPanel pnlFeedbackCard;
    private javax.swing.JPanel pnlNavAssessments;
    private javax.swing.JPanel pnlNavDashboard;
    private javax.swing.JPanel pnlNavFeedback;
    private javax.swing.JPanel pnlNavGrades;
    private javax.swing.JPanel pnlNavLogout;
    private javax.swing.JPanel pnlNavMyClasses;
    private javax.swing.JPanel pnlNavProfile;
    private javax.swing.JPanel pnlResultsCard;
    private javax.swing.JPanel sidebar;
    private javax.swing.JScrollPane spLectAssFeedback;
    private javax.swing.JTextArea taLectAssFeedback;
    private javax.swing.JPanel top;
    private javax.swing.JPanel topTitle;
    private javax.swing.JPanel topUserInfo;
    private javax.swing.JLabel txtRegisterNewClasses;
    // End of variables declaration//GEN-END:variables
}
