/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// my packages
package Student;

import Classes.ClassData;
import Classes.RegisteredClassData;
import Classes.StudentData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import Classes.ClassInfo;
import Classes.RegisteredClass;
import Classes.Student;
import Classes.Session;
import Login.AFS_LoginPage;

public class StudentDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentDashboard.class.getName());

    /**
     * Creates new form StudentDashboard
     */
    public StudentDashboard() {
        initComponents();
        
        setSize(1031, 643); 
        setLocationRelativeTo(null);
        
        loadWelcomeName();
        loadHeaderFromSession();
    }
    
    private void loadWelcomeName() {
        String sid = Session.getStudentId();
        if (sid == null || sid.trim().isEmpty()) {
            Name.setText("Student"); // change lblWelcomeName to your actual label name
            return;
        }

        StudentData sd = new StudentData();
        Student s = sd.findByStudentId(sid.trim());

        if (s != null && s.getName() != null && !s.getName().trim().isEmpty()) {
            Name.setText(s.getName().trim());
        } else {
            Name.setText("Student");
        }
    }
    
    private void loadHeaderFromSession() {
        String sid = Session.getStudentId();
        sid = (sid == null) ? "" : sid.trim();

        StudentID.setText(!sid.isBlank() ? sid : "TPXXXXXX");
        StudentRole.setText("Student");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbBase = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        gap1 = new javax.swing.JPanel();
        pnlAFSlogo = new javax.swing.JPanel();
        lblAFSlogo = new javax.swing.JLabel();
        gap2 = new javax.swing.JPanel();
        pnlNavDashboard = new javax.swing.JPanel();
        btnNavDashboard = new javax.swing.JButton();
        pnlNavMyClasses = new javax.swing.JPanel();
        btnNavMyClasses = new javax.swing.JButton();
        pnlNavAssessments = new javax.swing.JPanel();
        btnNavAssessments = new javax.swing.JButton();
        pnlNavGrades = new javax.swing.JPanel();
        btnNavGrades = new javax.swing.JButton();
        pnlNavFeedback = new javax.swing.JPanel();
        btnNavFeedback = new javax.swing.JButton();
        pnlNavProfile = new javax.swing.JPanel();
        btnNavProfile = new javax.swing.JButton();
        pnlNavLogout = new javax.swing.JPanel();
        btnNavLogout = new javax.swing.JButton();
        gap3 = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        topTitle = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        topUserInfo = new javax.swing.JPanel();
        StudentProfilePic = new javax.swing.JLabel();
        StudentRole = new javax.swing.JLabel();
        StudentID = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        btnQuickRegisterClass = new javax.swing.JButton();
        btnQuickAddFeedback = new javax.swing.JButton();
        QuickViewSchedule = new javax.swing.JButton();
        txtQuickAction = new javax.swing.JLabel();
        txtAnnouncements = new javax.swing.JLabel();
        txtAssessments = new javax.swing.JLabel();
        pnlAnnouncements = new javax.swing.JPanel();
        lblAnnouncement1 = new javax.swing.JLabel();
        lblAnnouncement2 = new javax.swing.JLabel();
        lblAnnouncement3 = new javax.swing.JLabel();
        lblAnnouncement4 = new javax.swing.JLabel();
        lblAnnouncement6 = new javax.swing.JLabel();
        lblAnnouncement5 = new javax.swing.JLabel();
        lblAnnouncement7 = new javax.swing.JLabel();
        lblAnnouncement8 = new javax.swing.JLabel();
        lblAnnouncement9 = new javax.swing.JLabel();
        pnlAssessments = new javax.swing.JPanel();
        pnlAssessmentCard1 = new javax.swing.JPanel();
        pnlAssessment1 = new javax.swing.JLabel();
        pnlAssessment2 = new javax.swing.JLabel();
        pnlAssessment3 = new javax.swing.JLabel();
        pnlAssessmentCard4 = new javax.swing.JPanel();
        pnlAssessment4 = new javax.swing.JLabel();
        pnlAssessment5 = new javax.swing.JLabel();
        pnlAssessment6 = new javax.swing.JLabel();
        pnlAssessmentCard5 = new javax.swing.JPanel();
        pnlAssessment7 = new javax.swing.JLabel();
        pnlAssessment8 = new javax.swing.JLabel();
        pnlAssessment9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Dashboard");
        setResizable(false);

        dbBase.setBackground(new java.awt.Color(255, 255, 255));
        dbBase.setLayout(new java.awt.BorderLayout());

        sidebar.setBackground(new java.awt.Color(24, 29, 49));
        sidebar.setPreferredSize(new java.awt.Dimension(209, 643));
        sidebar.setLayout(new javax.swing.BoxLayout(sidebar, javax.swing.BoxLayout.Y_AXIS));

        gap1.setBackground(new java.awt.Color(24, 29, 49));
        gap1.setPreferredSize(new java.awt.Dimension(209, 43));

        javax.swing.GroupLayout gap1Layout = new javax.swing.GroupLayout(gap1);
        gap1.setLayout(gap1Layout);
        gap1Layout.setHorizontalGroup(
            gap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        gap1Layout.setVerticalGroup(
            gap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        sidebar.add(gap1);

        pnlAFSlogo.setBackground(new java.awt.Color(24, 29, 49));

        lblAFSlogo.setBackground(new java.awt.Color(24, 29, 49));
        lblAFSlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AFS Logo.png"))); // NOI18N
        lblAFSlogo.setText("jLabel1");

        javax.swing.GroupLayout pnlAFSlogoLayout = new javax.swing.GroupLayout(pnlAFSlogo);
        pnlAFSlogo.setLayout(pnlAFSlogoLayout);
        pnlAFSlogoLayout.setHorizontalGroup(
            pnlAFSlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAFSlogoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAFSlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlAFSlogoLayout.setVerticalGroup(
            pnlAFSlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAFSlogoLayout.createSequentialGroup()
                .addComponent(lblAFSlogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(pnlAFSlogo);

        gap2.setBackground(new java.awt.Color(24, 29, 49));
        gap2.setPreferredSize(new java.awt.Dimension(209, 43));

        javax.swing.GroupLayout gap2Layout = new javax.swing.GroupLayout(gap2);
        gap2.setLayout(gap2Layout);
        gap2Layout.setHorizontalGroup(
            gap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        gap2Layout.setVerticalGroup(
            gap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        sidebar.add(gap2);

        pnlNavDashboard.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavDashboard.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavDashboard.setBackground(new java.awt.Color(24, 29, 49));
        btnNavDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavDashboard.setForeground(new java.awt.Color(166, 199, 155));
        btnNavDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ClickDb.png"))); // NOI18N
        btnNavDashboard.setText("   Dashboard");
        btnNavDashboard.setBorder(null);
        btnNavDashboard.setBorderPainted(false);
        btnNavDashboard.setContentAreaFilled(false);
        btnNavDashboard.setFocusPainted(false);
        btnNavDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavDashboard.setPreferredSize(new java.awt.Dimension(92, 40));
        btnNavDashboard.setVerifyInputWhenFocusTarget(false);
        btnNavDashboard.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNavDashboard.addActionListener(this::btnNavDashboardActionPerformed);

        javax.swing.GroupLayout pnlNavDashboardLayout = new javax.swing.GroupLayout(pnlNavDashboard);
        pnlNavDashboard.setLayout(pnlNavDashboardLayout);
        pnlNavDashboardLayout.setHorizontalGroup(
            pnlNavDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavDashboardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnNavDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlNavDashboardLayout.setVerticalGroup(
            pnlNavDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNavDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidebar.add(pnlNavDashboard);

        pnlNavMyClasses.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavMyClasses.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavMyClasses.setBackground(new java.awt.Color(24, 29, 49));
        btnNavMyClasses.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavMyClasses.setForeground(new java.awt.Color(255, 255, 255));
        btnNavMyClasses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconClass.png"))); // NOI18N
        btnNavMyClasses.setText("   My Classes");
        btnNavMyClasses.setBorder(null);
        btnNavMyClasses.setBorderPainted(false);
        btnNavMyClasses.setContentAreaFilled(false);
        btnNavMyClasses.setFocusPainted(false);
        btnNavMyClasses.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavMyClasses.addActionListener(this::btnNavMyClassesActionPerformed);

        javax.swing.GroupLayout pnlNavMyClassesLayout = new javax.swing.GroupLayout(pnlNavMyClasses);
        pnlNavMyClasses.setLayout(pnlNavMyClassesLayout);
        pnlNavMyClassesLayout.setHorizontalGroup(
            pnlNavMyClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavMyClassesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNavMyClasses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavMyClassesLayout.setVerticalGroup(
            pnlNavMyClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavMyClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNavMyClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavMyClasses);

        pnlNavAssessments.setBackground(new java.awt.Color(20, 24, 49));
        pnlNavAssessments.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavAssessments.setBackground(new java.awt.Color(24, 29, 49));
        btnNavAssessments.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavAssessments.setForeground(new java.awt.Color(255, 255, 255));
        btnNavAssessments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconAss.png"))); // NOI18N
        btnNavAssessments.setText("  Assessments");
        btnNavAssessments.setBorder(null);
        btnNavAssessments.setBorderPainted(false);
        btnNavAssessments.setContentAreaFilled(false);
        btnNavAssessments.setFocusPainted(false);
        btnNavAssessments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavAssessments.addActionListener(this::btnNavAssessmentsActionPerformed);

        javax.swing.GroupLayout pnlNavAssessmentsLayout = new javax.swing.GroupLayout(pnlNavAssessments);
        pnlNavAssessments.setLayout(pnlNavAssessmentsLayout);
        pnlNavAssessmentsLayout.setHorizontalGroup(
            pnlNavAssessmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavAssessmentsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNavAssessments, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlNavAssessmentsLayout.setVerticalGroup(
            pnlNavAssessmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavAssessmentsLayout.createSequentialGroup()
                .addComponent(btnNavAssessments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavAssessments);

        pnlNavGrades.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavGrades.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavGrades.setBackground(new java.awt.Color(24, 29, 49));
        btnNavGrades.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavGrades.setForeground(new java.awt.Color(255, 255, 255));
        btnNavGrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconGrading.png"))); // NOI18N
        btnNavGrades.setText("   Grades");
        btnNavGrades.setBorder(null);
        btnNavGrades.setBorderPainted(false);
        btnNavGrades.setContentAreaFilled(false);
        btnNavGrades.setFocusPainted(false);
        btnNavGrades.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavGrades.addActionListener(this::btnNavGradesActionPerformed);

        javax.swing.GroupLayout pnlNavGradesLayout = new javax.swing.GroupLayout(pnlNavGrades);
        pnlNavGrades.setLayout(pnlNavGradesLayout);
        pnlNavGradesLayout.setHorizontalGroup(
            pnlNavGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavGradesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnNavGrades)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavGradesLayout.setVerticalGroup(
            pnlNavGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavGradesLayout.createSequentialGroup()
                .addComponent(btnNavGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavGrades);

        pnlNavFeedback.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavFeedback.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavFeedback.setBackground(new java.awt.Color(24, 29, 49));
        btnNavFeedback.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnNavFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconFeedback.png"))); // NOI18N
        btnNavFeedback.setText("   Feedback");
        btnNavFeedback.setBorder(null);
        btnNavFeedback.setBorderPainted(false);
        btnNavFeedback.setContentAreaFilled(false);
        btnNavFeedback.setFocusPainted(false);
        btnNavFeedback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavFeedback.addActionListener(this::btnNavFeedbackActionPerformed);

        javax.swing.GroupLayout pnlNavFeedbackLayout = new javax.swing.GroupLayout(pnlNavFeedback);
        pnlNavFeedback.setLayout(pnlNavFeedbackLayout);
        pnlNavFeedbackLayout.setHorizontalGroup(
            pnlNavFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavFeedbackLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNavFeedback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavFeedbackLayout.setVerticalGroup(
            pnlNavFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavFeedbackLayout.createSequentialGroup()
                .addComponent(btnNavFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavFeedback);

        pnlNavProfile.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavProfile.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavProfile.setBackground(new java.awt.Color(24, 29, 49));
        btnNavProfile.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnNavProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconProfile.png"))); // NOI18N
        btnNavProfile.setText("   Profile");
        btnNavProfile.setBorder(null);
        btnNavProfile.setBorderPainted(false);
        btnNavProfile.setContentAreaFilled(false);
        btnNavProfile.setFocusPainted(false);
        btnNavProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavProfile.addActionListener(this::btnNavProfileActionPerformed);

        javax.swing.GroupLayout pnlNavProfileLayout = new javax.swing.GroupLayout(pnlNavProfile);
        pnlNavProfile.setLayout(pnlNavProfileLayout);
        pnlNavProfileLayout.setHorizontalGroup(
            pnlNavProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavProfileLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNavProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavProfileLayout.setVerticalGroup(
            pnlNavProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavProfileLayout.createSequentialGroup()
                .addComponent(btnNavProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavProfile);

        pnlNavLogout.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavLogout.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavLogout.setBackground(new java.awt.Color(24, 29, 49));
        btnNavLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnNavLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconLogout.png"))); // NOI18N
        btnNavLogout.setText("   Logout");
        btnNavLogout.setAutoscrolls(true);
        btnNavLogout.setBorder(null);
        btnNavLogout.setBorderPainted(false);
        btnNavLogout.setContentAreaFilled(false);
        btnNavLogout.setFocusPainted(false);
        btnNavLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavLogout.addActionListener(this::btnNavLogoutActionPerformed);

        javax.swing.GroupLayout pnlNavLogoutLayout = new javax.swing.GroupLayout(pnlNavLogout);
        pnlNavLogout.setLayout(pnlNavLogoutLayout);
        pnlNavLogoutLayout.setHorizontalGroup(
            pnlNavLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLogoutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNavLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavLogoutLayout.setVerticalGroup(
            pnlNavLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavLogoutLayout.createSequentialGroup()
                .addComponent(btnNavLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavLogout);

        gap3.setBackground(new java.awt.Color(24, 29, 49));
        gap3.setPreferredSize(new java.awt.Dimension(209, 800));

        javax.swing.GroupLayout gap3Layout = new javax.swing.GroupLayout(gap3);
        gap3.setLayout(gap3Layout);
        gap3Layout.setHorizontalGroup(
            gap3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        gap3Layout.setVerticalGroup(
            gap3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        sidebar.add(gap3);

        dbBase.add(sidebar, java.awt.BorderLayout.WEST);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new java.awt.BorderLayout());

        top.setBackground(new java.awt.Color(255, 255, 255));
        top.setPreferredSize(new java.awt.Dimension(822, 90));
        top.setLayout(new java.awt.BorderLayout());

        topTitle.setBackground(new java.awt.Color(255, 255, 255));
        topTitle.setPreferredSize(new java.awt.Dimension(100, 91));

        txtDashboard.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        txtDashboard.setText("Dashboard");

        lblWelcome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblWelcome.setText("Welcome,");

        Name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(166, 199, 155));
        Name.setText("XX XXXX XXXX");

        javax.swing.GroupLayout topTitleLayout = new javax.swing.GroupLayout(topTitle);
        topTitle.setLayout(topTitleLayout);
        topTitleLayout.setHorizontalGroup(
            topTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topTitleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(topTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDashboard)
                    .addGroup(topTitleLayout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(18, 18, 18)
                        .addComponent(Name)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        topTitleLayout.setVerticalGroup(
            topTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topTitleLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtDashboard)
                .addGap(24, 24, 24)
                .addGroup(topTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(Name)))
        );

        top.add(topTitle, java.awt.BorderLayout.CENTER);

        topUserInfo.setBackground(new java.awt.Color(255, 255, 255));
        topUserInfo.setPreferredSize(new java.awt.Dimension(150, 91));

        StudentProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User Icon.png"))); // NOI18N
        StudentProfilePic.setText("jLabel2");

        StudentRole.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        StudentRole.setText("Student");

        StudentID.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        StudentID.setText("TPXXXXXX");

        javax.swing.GroupLayout topUserInfoLayout = new javax.swing.GroupLayout(topUserInfo);
        topUserInfo.setLayout(topUserInfoLayout);
        topUserInfoLayout.setHorizontalGroup(
            topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addGroup(topUserInfoLayout.createSequentialGroup()
                        .addComponent(StudentRole, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        topUserInfoLayout.setVerticalGroup(
            topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topUserInfoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topUserInfoLayout.createSequentialGroup()
                        .addComponent(StudentID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StudentRole)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        top.add(topUserInfo, java.awt.BorderLayout.EAST);

        main.add(top, java.awt.BorderLayout.NORTH);

        content.setBackground(new java.awt.Color(255, 255, 255));

        btnQuickRegisterClass.setBackground(new java.awt.Color(109, 139, 82));
        btnQuickRegisterClass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQuickRegisterClass.setForeground(new java.awt.Color(255, 255, 255));
        btnQuickRegisterClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/QARegister.png"))); // NOI18N
        btnQuickRegisterClass.setText("Register Class    ");
        btnQuickRegisterClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnQuickRegisterClass.setBorderPainted(false);
        btnQuickRegisterClass.setFocusPainted(false);
        btnQuickRegisterClass.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnQuickRegisterClass.addActionListener(this::btnQuickRegisterClassActionPerformed);

        btnQuickAddFeedback.setBackground(new java.awt.Color(109, 139, 82));
        btnQuickAddFeedback.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnQuickAddFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnQuickAddFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/QAAssessment.png"))); // NOI18N
        btnQuickAddFeedback.setText("Create Comment    ");
        btnQuickAddFeedback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnQuickAddFeedback.setBorderPainted(false);
        btnQuickAddFeedback.setFocusPainted(false);
        btnQuickAddFeedback.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnQuickAddFeedback.addActionListener(this::btnQuickAddFeedbackActionPerformed);

        QuickViewSchedule.setBackground(new java.awt.Color(109, 139, 82));
        QuickViewSchedule.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        QuickViewSchedule.setForeground(new java.awt.Color(255, 255, 255));
        QuickViewSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/QAButton2.png"))); // NOI18N
        QuickViewSchedule.setText("View Schedule    ");
        QuickViewSchedule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        QuickViewSchedule.setBorderPainted(false);
        QuickViewSchedule.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        QuickViewSchedule.addActionListener(this::QuickViewScheduleActionPerformed);

        txtQuickAction.setBackground(new java.awt.Color(255, 255, 255));
        txtQuickAction.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        txtQuickAction.setText("Quick Actions:");

        txtAnnouncements.setBackground(new java.awt.Color(255, 255, 255));
        txtAnnouncements.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        txtAnnouncements.setText("Announcements:");

        txtAssessments.setBackground(new java.awt.Color(255, 255, 255));
        txtAssessments.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        txtAssessments.setText("Assessments:");

        pnlAnnouncements.setBackground(new java.awt.Color(255, 255, 255));
        pnlAnnouncements.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(204, 204, 204)));

        lblAnnouncement1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAnnouncement1.setText("Class Registration Deadline");

        lblAnnouncement2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnnouncement2.setText("Reminder: Registration deadline for new ");

        lblAnnouncement3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnnouncement3.setText(" list of required classes for your course and");

        lblAnnouncement4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAnnouncement4.setText("29 Nov 2025, 10.18am");

        lblAnnouncement6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnnouncement6.setText("is this Friday, at 6:00pm. Be sure to check the");

        lblAnnouncement5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAnnouncement5.setText("OODJ Assignment Grades Released");

        lblAnnouncement7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnnouncement7.setText("register the right classes.");

        lblAnnouncement8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAnnouncement8.setText("29 Nov 2025, 10.18am");

        lblAnnouncement9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnnouncement9.setText("View results for OODJ Assignment.");

        javax.swing.GroupLayout pnlAnnouncementsLayout = new javax.swing.GroupLayout(pnlAnnouncements);
        pnlAnnouncements.setLayout(pnlAnnouncementsLayout);
        pnlAnnouncementsLayout.setHorizontalGroup(
            pnlAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnnouncementsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAnnouncement7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAnnouncement9, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(lblAnnouncement8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnnouncement5)
                    .addComponent(lblAnnouncement4)
                    .addComponent(lblAnnouncement1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnnouncement3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAnnouncement2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAnnouncement6))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlAnnouncementsLayout.setVerticalGroup(
            pnlAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnnouncementsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAnnouncement1)
                .addGap(5, 5, 5)
                .addComponent(lblAnnouncement4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAnnouncement2)
                .addGap(2, 2, 2)
                .addComponent(lblAnnouncement6)
                .addGap(2, 2, 2)
                .addComponent(lblAnnouncement3)
                .addGap(2, 2, 2)
                .addComponent(lblAnnouncement7)
                .addGap(20, 20, 20)
                .addComponent(lblAnnouncement5)
                .addGap(5, 5, 5)
                .addComponent(lblAnnouncement8)
                .addGap(18, 18, 18)
                .addComponent(lblAnnouncement9)
                .addGap(46, 46, 46))
        );

        pnlAssessments.setBackground(new java.awt.Color(255, 255, 255));
        pnlAssessments.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(204, 204, 204)));

        pnlAssessmentCard1.setBackground(new java.awt.Color(255, 255, 204));
        pnlAssessmentCard1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        pnlAssessment1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pnlAssessment1.setText("OODJ Trial Exam");

        pnlAssessment2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAssessment2.setText("Hand out date: 20 Jan 2026, 10:00am");

        pnlAssessment3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAssessment3.setText("Hand in date:   20 Jan 2026, 11:59pm");

        javax.swing.GroupLayout pnlAssessmentCard1Layout = new javax.swing.GroupLayout(pnlAssessmentCard1);
        pnlAssessmentCard1.setLayout(pnlAssessmentCard1Layout);
        pnlAssessmentCard1Layout.setHorizontalGroup(
            pnlAssessmentCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssessmentCard1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlAssessment1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAssessmentCard1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAssessmentCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAssessment3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAssessment2))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlAssessmentCard1Layout.setVerticalGroup(
            pnlAssessmentCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssessmentCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAssessment1)
                .addGap(2, 2, 2)
                .addComponent(pnlAssessment2)
                .addGap(2, 2, 2)
                .addComponent(pnlAssessment3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAssessmentCard4.setBackground(new java.awt.Color(255, 255, 204));
        pnlAssessmentCard4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        pnlAssessment4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pnlAssessment4.setText("SNA Week 3 Report");

        pnlAssessment5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAssessment5.setText("Hand out date: 17 Feb 2026, 10:00am");

        pnlAssessment6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAssessment6.setText("Hand in date:   18 Feb 2026, 11:59pm");

        javax.swing.GroupLayout pnlAssessmentCard4Layout = new javax.swing.GroupLayout(pnlAssessmentCard4);
        pnlAssessmentCard4.setLayout(pnlAssessmentCard4Layout);
        pnlAssessmentCard4Layout.setHorizontalGroup(
            pnlAssessmentCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssessmentCard4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlAssessment4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAssessmentCard4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAssessmentCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAssessment6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAssessment5))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlAssessmentCard4Layout.setVerticalGroup(
            pnlAssessmentCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssessmentCard4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAssessment4)
                .addGap(2, 2, 2)
                .addComponent(pnlAssessment5)
                .addGap(2, 2, 2)
                .addComponent(pnlAssessment6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAssessmentCard5.setBackground(new java.awt.Color(255, 255, 204));
        pnlAssessmentCard5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        pnlAssessment7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pnlAssessment7.setText("DTM Quiz");

        pnlAssessment8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAssessment8.setText("Hand out date: 13 Feb 2026, 10:00am");

        pnlAssessment9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlAssessment9.setText("Hand in date:   29 Feb 2026, 11:59pm");

        javax.swing.GroupLayout pnlAssessmentCard5Layout = new javax.swing.GroupLayout(pnlAssessmentCard5);
        pnlAssessmentCard5.setLayout(pnlAssessmentCard5Layout);
        pnlAssessmentCard5Layout.setHorizontalGroup(
            pnlAssessmentCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssessmentCard5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlAssessment7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAssessmentCard5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAssessmentCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAssessment9, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAssessment8))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlAssessmentCard5Layout.setVerticalGroup(
            pnlAssessmentCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssessmentCard5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAssessment7)
                .addGap(2, 2, 2)
                .addComponent(pnlAssessment8)
                .addGap(2, 2, 2)
                .addComponent(pnlAssessment9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAssessmentsLayout = new javax.swing.GroupLayout(pnlAssessments);
        pnlAssessments.setLayout(pnlAssessmentsLayout);
        pnlAssessmentsLayout.setHorizontalGroup(
            pnlAssessmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssessmentsLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(pnlAssessmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAssessmentCard1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAssessmentCard4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAssessmentCard5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        pnlAssessmentsLayout.setVerticalGroup(
            pnlAssessmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssessmentsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlAssessmentCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlAssessmentCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlAssessmentCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addComponent(btnQuickRegisterClass, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnQuickAddFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(QuickViewSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(txtQuickAction)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(pnlAnnouncements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlAssessments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(txtAnnouncements)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAssessments)
                        .addGap(283, 283, 283))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtQuickAction)
                .addGap(10, 10, 10)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuickRegisterClass, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuickAddFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuickViewSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnnouncements)
                    .addComponent(txtAssessments))
                .addGap(10, 10, 10)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAssessments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAnnouncements, javax.swing.GroupLayout.PREFERRED_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        main.add(content, java.awt.BorderLayout.CENTER);

        dbBase.add(main, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavDashboardActionPerformed

    private void btnNavAssessmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavAssessmentsActionPerformed
        new StudentAssessments().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavAssessmentsActionPerformed

    private void btnNavProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavProfileActionPerformed
        new StudentProfile().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavProfileActionPerformed

    private void btnQuickRegisterClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickRegisterClassActionPerformed
        new StudentRegisterClass().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuickRegisterClassActionPerformed

    private void btnQuickAddFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickAddFeedbackActionPerformed
  
        if (!Session.isLoggedIn() || Session.getStudentId() == null) {
            JOptionPane.showMessageDialog(this, "No active student session.");
            return;
        }

        String studentId = Session.getStudentId().trim();

        RegisteredClassData rcData = new RegisteredClassData();
        List<RegisteredClass> regs = rcData.findByStudentId(studentId);

        if (regs == null || regs.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "You have no registered classes.\nRegister a class before creating a comment.");
            return;
        }

        // Build choices using class names
        ClassData classData = new ClassData();
        List<String> classIds = new ArrayList<>();
        List<String> labels = new ArrayList<>();

        for (RegisteredClass rc : regs) {
            if (rc == null || rc.getClassID() == null) continue;

            String classId = rc.getClassID().trim();
            if (classIds.contains(classId)) continue;

            ClassInfo ci = classData.findById(classId);
            String label = (ci == null) ? classId : ci.getName();

            classIds.add(classId);
            labels.add(label);
        }

        String selectedLabel = (String) JOptionPane.showInputDialog(
                this,
                "Select a class to comment on:",
                "Create Comment",
                JOptionPane.QUESTION_MESSAGE,
                null,
                labels.toArray(),
                labels.get(0)
        );

        if (selectedLabel == null) return; // user canceled

        // Map label back to classId
        int index = labels.indexOf(selectedLabel);
        String selectedClassId = classIds.get(index);

        Session.setSelectedClassId(selectedClassId);

        new StudentFeedbackForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuickAddFeedbackActionPerformed

    private void QuickViewScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickViewScheduleActionPerformed
        new StudentClassSchedule().setVisible(true);
        dispose();
    }//GEN-LAST:event_QuickViewScheduleActionPerformed

    private void btnNavMyClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavMyClassesActionPerformed
        new StudentMyClasses().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavMyClassesActionPerformed

    private void btnNavGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavGradesActionPerformed
        new StudentGrades().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavGradesActionPerformed

    private void btnNavFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavFeedbackActionPerformed
        new StudentFeedback().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavFeedbackActionPerformed

    private void btnNavLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavLogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
                "Logging out?", 
                "Confirmation", 
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new AFS_LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnNavLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JButton QuickViewSchedule;
    private javax.swing.JLabel StudentID;
    private javax.swing.JLabel StudentProfilePic;
    private javax.swing.JLabel StudentRole;
    private javax.swing.JButton btnNavAssessments;
    private javax.swing.JButton btnNavDashboard;
    private javax.swing.JButton btnNavFeedback;
    private javax.swing.JButton btnNavGrades;
    private javax.swing.JButton btnNavLogout;
    private javax.swing.JButton btnNavMyClasses;
    private javax.swing.JButton btnNavProfile;
    private javax.swing.JButton btnQuickAddFeedback;
    private javax.swing.JButton btnQuickRegisterClass;
    private javax.swing.JPanel content;
    private javax.swing.JPanel dbBase;
    private javax.swing.JPanel gap1;
    private javax.swing.JPanel gap2;
    private javax.swing.JPanel gap3;
    private javax.swing.JLabel lblAFSlogo;
    private javax.swing.JLabel lblAnnouncement1;
    private javax.swing.JLabel lblAnnouncement2;
    private javax.swing.JLabel lblAnnouncement3;
    private javax.swing.JLabel lblAnnouncement4;
    private javax.swing.JLabel lblAnnouncement5;
    private javax.swing.JLabel lblAnnouncement6;
    private javax.swing.JLabel lblAnnouncement7;
    private javax.swing.JLabel lblAnnouncement8;
    private javax.swing.JLabel lblAnnouncement9;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnlAFSlogo;
    private javax.swing.JPanel pnlAnnouncements;
    private javax.swing.JLabel pnlAssessment1;
    private javax.swing.JLabel pnlAssessment2;
    private javax.swing.JLabel pnlAssessment3;
    private javax.swing.JLabel pnlAssessment4;
    private javax.swing.JLabel pnlAssessment5;
    private javax.swing.JLabel pnlAssessment6;
    private javax.swing.JLabel pnlAssessment7;
    private javax.swing.JLabel pnlAssessment8;
    private javax.swing.JLabel pnlAssessment9;
    private javax.swing.JPanel pnlAssessmentCard1;
    private javax.swing.JPanel pnlAssessmentCard4;
    private javax.swing.JPanel pnlAssessmentCard5;
    private javax.swing.JPanel pnlAssessments;
    private javax.swing.JPanel pnlNavAssessments;
    private javax.swing.JPanel pnlNavDashboard;
    private javax.swing.JPanel pnlNavFeedback;
    private javax.swing.JPanel pnlNavGrades;
    private javax.swing.JPanel pnlNavLogout;
    private javax.swing.JPanel pnlNavMyClasses;
    private javax.swing.JPanel pnlNavProfile;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel top;
    private javax.swing.JPanel topTitle;
    private javax.swing.JPanel topUserInfo;
    private javax.swing.JLabel txtAnnouncements;
    private javax.swing.JLabel txtAssessments;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtQuickAction;
    // End of variables declaration//GEN-END:variables
}
