/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// my packages
package Student;
import Classes.ClassData;
import Classes.RegisteredClassData;
import Classes.StudentData;
import Classes.ModuleResultData;
import Classes.ModuleResult;
import Classes.Student;
import Classes.ClassInfo;
import Classes.RegisteredClass;
import Classes.FilePath;
import Classes.Session;
import Login.AFS_LoginPage;

// java packages
import java.awt.*;
import java.time.LocalDate;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.List;
import java.util.Collections;

/**
 *
 * @author User
 */
public class StudentRegisterClass extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentRegisterClass.class.getName());
    
    // table data
    private javax.swing.table.DefaultTableModel tableModel;
    private final java.util.List<String[]> allRows = new java.util.ArrayList<>();
    private final Map<String, String> moduleLectToModule = new HashMap<>();
    private final Map<String, Integer> registeredCountByClass = new HashMap<>();
    private final Map<String, Set<String>> registeredStudentsByClass = new HashMap<>();
    private final Set<String> requiredModuleIds = new HashSet<>();

    /**
     * Creates new form StudentRegisterClass
     */
    public StudentRegisterClass() {
        initComponents();
        initCustom();
        
        tblAvailableClasses.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        
        setSize(1031, 643); 
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        // available classes table
        styleTableHeader();
        styleTableCells();
        tblAvailableClasses.setRowHeight(44);
        tblAvailableClasses.getTableHeader().setPreferredSize(new Dimension(100, 40));
        tblAvailableClasses.setGridColor(Color.BLACK);
        tblAvailableClasses.setShowHorizontalLines(true);
        tblAvailableClasses.setShowVerticalLines(true);
        tblAvailableClasses.getColumnModel().getColumn(0).setPreferredWidth(90);   // class ID
        tblAvailableClasses.getColumnModel().getColumn(1).setPreferredWidth(169);  // name
        tblAvailableClasses.getColumnModel().getColumn(2).setPreferredWidth(70);   // type
        tblAvailableClasses.getColumnModel().getColumn(3).setPreferredWidth(75);   // day
        tblAvailableClasses.getColumnModel().getColumn(4).setPreferredWidth(110);   // time slot
        tblAvailableClasses.getColumnModel().getColumn(5).setPreferredWidth(68);   // venue
        tblAvailableClasses.getColumnModel().getColumn(6).setPreferredWidth(60);   // capacity
        tblAvailableClasses.getColumnModel().getColumn(7).setPreferredWidth(70);   // status
        
        spAvailableClassesTable.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spAvailableClassesTable.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        tblAvailableClasses.setFillsViewportHeight(true);
        
        loadHeaderFromSession();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbBase = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        gap1 = new javax.swing.JPanel();
        pnlAFSlogo = new javax.swing.JPanel();
        lblAFSlogo = new javax.swing.JLabel();
        gap2 = new javax.swing.JPanel();
        pnlNavDashboard = new javax.swing.JPanel();
        btnNavDashboard = new javax.swing.JButton();
        pnlNavMyClasses = new javax.swing.JPanel();
        btnNavMyClasses = new javax.swing.JButton();
        pnlNavAssessments = new javax.swing.JPanel();
        btnNavAssessments = new javax.swing.JButton();
        pnlNavGrades = new javax.swing.JPanel();
        btnNavGrades = new javax.swing.JButton();
        pnlNavFeedback = new javax.swing.JPanel();
        btnNavFeedback = new javax.swing.JButton();
        pnlNavProfile = new javax.swing.JPanel();
        btnNavProfile = new javax.swing.JButton();
        pnlNavLogout = new javax.swing.JPanel();
        btnNavLogout = new javax.swing.JButton();
        gap3 = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        topTitle = new javax.swing.JPanel();
        txtRegisterNewClasses = new javax.swing.JLabel();
        topUserInfo = new javax.swing.JPanel();
        StudentProfilePic = new javax.swing.JLabel();
        StudentRole = new javax.swing.JLabel();
        StudentID = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        lblFilter = new javax.swing.JLabel();
        lblModule = new javax.swing.JLabel();
        cbModule = new javax.swing.JComboBox<>();
        lblType = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        lblAvailableClasses = new javax.swing.JLabel();
        btnRegisterSelectedClasses = new javax.swing.JButton();
        spAvailableClassesTable = new javax.swing.JScrollPane();
        tblAvailableClasses = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Class Registration");
        setResizable(false);

        dbBase.setBackground(new java.awt.Color(255, 255, 255));
        dbBase.setLayout(new java.awt.BorderLayout());

        sidebar.setBackground(new java.awt.Color(24, 29, 49));
        sidebar.setPreferredSize(new java.awt.Dimension(209, 643));
        sidebar.setLayout(new javax.swing.BoxLayout(sidebar, javax.swing.BoxLayout.Y_AXIS));

        gap1.setBackground(new java.awt.Color(24, 29, 49));
        gap1.setPreferredSize(new java.awt.Dimension(209, 43));

        javax.swing.GroupLayout gap1Layout = new javax.swing.GroupLayout(gap1);
        gap1.setLayout(gap1Layout);
        gap1Layout.setHorizontalGroup(
            gap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        gap1Layout.setVerticalGroup(
            gap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        sidebar.add(gap1);

        pnlAFSlogo.setBackground(new java.awt.Color(24, 29, 49));

        lblAFSlogo.setBackground(new java.awt.Color(24, 29, 49));
        lblAFSlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AFS Logo.png"))); // NOI18N
        lblAFSlogo.setText("jLabel1");

        javax.swing.GroupLayout pnlAFSlogoLayout = new javax.swing.GroupLayout(pnlAFSlogo);
        pnlAFSlogo.setLayout(pnlAFSlogoLayout);
        pnlAFSlogoLayout.setHorizontalGroup(
            pnlAFSlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAFSlogoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAFSlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlAFSlogoLayout.setVerticalGroup(
            pnlAFSlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAFSlogoLayout.createSequentialGroup()
                .addComponent(lblAFSlogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(pnlAFSlogo);

        gap2.setBackground(new java.awt.Color(24, 29, 49));
        gap2.setPreferredSize(new java.awt.Dimension(209, 43));

        javax.swing.GroupLayout gap2Layout = new javax.swing.GroupLayout(gap2);
        gap2.setLayout(gap2Layout);
        gap2Layout.setHorizontalGroup(
            gap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        gap2Layout.setVerticalGroup(
            gap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        sidebar.add(gap2);

        pnlNavDashboard.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavDashboard.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavDashboard.setBackground(new java.awt.Color(24, 29, 49));
        btnNavDashboard.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnNavDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconDb.png"))); // NOI18N
        btnNavDashboard.setText("   Dashboard");
        btnNavDashboard.setBorder(null);
        btnNavDashboard.setBorderPainted(false);
        btnNavDashboard.setContentAreaFilled(false);
        btnNavDashboard.setFocusPainted(false);
        btnNavDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavDashboard.setPreferredSize(new java.awt.Dimension(92, 40));
        btnNavDashboard.setVerifyInputWhenFocusTarget(false);
        btnNavDashboard.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNavDashboard.addActionListener(this::btnNavDashboardActionPerformed);

        javax.swing.GroupLayout pnlNavDashboardLayout = new javax.swing.GroupLayout(pnlNavDashboard);
        pnlNavDashboard.setLayout(pnlNavDashboardLayout);
        pnlNavDashboardLayout.setHorizontalGroup(
            pnlNavDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavDashboardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnNavDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlNavDashboardLayout.setVerticalGroup(
            pnlNavDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNavDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidebar.add(pnlNavDashboard);

        pnlNavMyClasses.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavMyClasses.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavMyClasses.setBackground(new java.awt.Color(24, 29, 49));
        btnNavMyClasses.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavMyClasses.setForeground(new java.awt.Color(166, 199, 155));
        btnNavMyClasses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ClickMC.png"))); // NOI18N
        btnNavMyClasses.setText("   My Classes");
        btnNavMyClasses.setBorder(null);
        btnNavMyClasses.setBorderPainted(false);
        btnNavMyClasses.setContentAreaFilled(false);
        btnNavMyClasses.setFocusPainted(false);
        btnNavMyClasses.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavMyClasses.addActionListener(this::btnNavMyClassesActionPerformed);

        javax.swing.GroupLayout pnlNavMyClassesLayout = new javax.swing.GroupLayout(pnlNavMyClasses);
        pnlNavMyClasses.setLayout(pnlNavMyClassesLayout);
        pnlNavMyClassesLayout.setHorizontalGroup(
            pnlNavMyClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavMyClassesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNavMyClasses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavMyClassesLayout.setVerticalGroup(
            pnlNavMyClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavMyClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNavMyClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavMyClasses);

        pnlNavAssessments.setBackground(new java.awt.Color(20, 24, 49));
        pnlNavAssessments.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavAssessments.setBackground(new java.awt.Color(24, 29, 49));
        btnNavAssessments.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavAssessments.setForeground(new java.awt.Color(255, 255, 255));
        btnNavAssessments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconAss.png"))); // NOI18N
        btnNavAssessments.setText("  Assessments");
        btnNavAssessments.setBorder(null);
        btnNavAssessments.setBorderPainted(false);
        btnNavAssessments.setContentAreaFilled(false);
        btnNavAssessments.setFocusPainted(false);
        btnNavAssessments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavAssessments.addActionListener(this::btnNavAssessmentsActionPerformed);

        javax.swing.GroupLayout pnlNavAssessmentsLayout = new javax.swing.GroupLayout(pnlNavAssessments);
        pnlNavAssessments.setLayout(pnlNavAssessmentsLayout);
        pnlNavAssessmentsLayout.setHorizontalGroup(
            pnlNavAssessmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavAssessmentsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNavAssessments, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlNavAssessmentsLayout.setVerticalGroup(
            pnlNavAssessmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavAssessmentsLayout.createSequentialGroup()
                .addComponent(btnNavAssessments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavAssessments);

        pnlNavGrades.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavGrades.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavGrades.setBackground(new java.awt.Color(24, 29, 49));
        btnNavGrades.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavGrades.setForeground(new java.awt.Color(255, 255, 255));
        btnNavGrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconGrading.png"))); // NOI18N
        btnNavGrades.setText("   Grades");
        btnNavGrades.setBorder(null);
        btnNavGrades.setBorderPainted(false);
        btnNavGrades.setContentAreaFilled(false);
        btnNavGrades.setFocusPainted(false);
        btnNavGrades.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavGrades.addActionListener(this::btnNavGradesActionPerformed);

        javax.swing.GroupLayout pnlNavGradesLayout = new javax.swing.GroupLayout(pnlNavGrades);
        pnlNavGrades.setLayout(pnlNavGradesLayout);
        pnlNavGradesLayout.setHorizontalGroup(
            pnlNavGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavGradesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnNavGrades)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavGradesLayout.setVerticalGroup(
            pnlNavGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavGradesLayout.createSequentialGroup()
                .addComponent(btnNavGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavGrades);

        pnlNavFeedback.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavFeedback.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavFeedback.setBackground(new java.awt.Color(24, 29, 49));
        btnNavFeedback.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnNavFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconFeedback.png"))); // NOI18N
        btnNavFeedback.setText("   Feedback");
        btnNavFeedback.setBorder(null);
        btnNavFeedback.setBorderPainted(false);
        btnNavFeedback.setContentAreaFilled(false);
        btnNavFeedback.setFocusPainted(false);
        btnNavFeedback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavFeedback.addActionListener(this::btnNavFeedbackActionPerformed);

        javax.swing.GroupLayout pnlNavFeedbackLayout = new javax.swing.GroupLayout(pnlNavFeedback);
        pnlNavFeedback.setLayout(pnlNavFeedbackLayout);
        pnlNavFeedbackLayout.setHorizontalGroup(
            pnlNavFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavFeedbackLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNavFeedback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavFeedbackLayout.setVerticalGroup(
            pnlNavFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavFeedbackLayout.createSequentialGroup()
                .addComponent(btnNavFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavFeedback);

        pnlNavProfile.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavProfile.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavProfile.setBackground(new java.awt.Color(24, 29, 49));
        btnNavProfile.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnNavProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconProfile.png"))); // NOI18N
        btnNavProfile.setText("   Profile");
        btnNavProfile.setBorder(null);
        btnNavProfile.setBorderPainted(false);
        btnNavProfile.setContentAreaFilled(false);
        btnNavProfile.setFocusPainted(false);
        btnNavProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavProfile.addActionListener(this::btnNavProfileActionPerformed);

        javax.swing.GroupLayout pnlNavProfileLayout = new javax.swing.GroupLayout(pnlNavProfile);
        pnlNavProfile.setLayout(pnlNavProfileLayout);
        pnlNavProfileLayout.setHorizontalGroup(
            pnlNavProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavProfileLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNavProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavProfileLayout.setVerticalGroup(
            pnlNavProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavProfileLayout.createSequentialGroup()
                .addComponent(btnNavProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavProfile);

        pnlNavLogout.setBackground(new java.awt.Color(24, 29, 49));
        pnlNavLogout.setPreferredSize(new java.awt.Dimension(209, 40));

        btnNavLogout.setBackground(new java.awt.Color(24, 29, 49));
        btnNavLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNavLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnNavLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconLogout.png"))); // NOI18N
        btnNavLogout.setText("   Logout");
        btnNavLogout.setAutoscrolls(true);
        btnNavLogout.setBorder(null);
        btnNavLogout.setBorderPainted(false);
        btnNavLogout.setContentAreaFilled(false);
        btnNavLogout.setFocusPainted(false);
        btnNavLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNavLogout.addActionListener(this::btnNavLogoutActionPerformed);

        javax.swing.GroupLayout pnlNavLogoutLayout = new javax.swing.GroupLayout(pnlNavLogout);
        pnlNavLogout.setLayout(pnlNavLogoutLayout);
        pnlNavLogoutLayout.setHorizontalGroup(
            pnlNavLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLogoutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNavLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavLogoutLayout.setVerticalGroup(
            pnlNavLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavLogoutLayout.createSequentialGroup()
                .addComponent(btnNavLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidebar.add(pnlNavLogout);

        gap3.setBackground(new java.awt.Color(24, 29, 49));
        gap3.setPreferredSize(new java.awt.Dimension(209, 800));

        javax.swing.GroupLayout gap3Layout = new javax.swing.GroupLayout(gap3);
        gap3.setLayout(gap3Layout);
        gap3Layout.setHorizontalGroup(
            gap3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        gap3Layout.setVerticalGroup(
            gap3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        sidebar.add(gap3);

        dbBase.add(sidebar, java.awt.BorderLayout.WEST);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new java.awt.BorderLayout());

        top.setBackground(new java.awt.Color(255, 255, 255));
        top.setPreferredSize(new java.awt.Dimension(822, 80));
        top.setLayout(new java.awt.BorderLayout());

        topTitle.setBackground(new java.awt.Color(255, 255, 255));
        topTitle.setPreferredSize(new java.awt.Dimension(100, 80));

        txtRegisterNewClasses.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        txtRegisterNewClasses.setText("Register New Classes");

        javax.swing.GroupLayout topTitleLayout = new javax.swing.GroupLayout(topTitle);
        topTitle.setLayout(topTitleLayout);
        topTitleLayout.setHorizontalGroup(
            topTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topTitleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtRegisterNewClasses)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        topTitleLayout.setVerticalGroup(
            topTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topTitleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtRegisterNewClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        top.add(topTitle, java.awt.BorderLayout.CENTER);

        topUserInfo.setBackground(new java.awt.Color(255, 255, 255));
        topUserInfo.setPreferredSize(new java.awt.Dimension(150, 80));

        StudentProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/User Icon.png"))); // NOI18N
        StudentProfilePic.setText("jLabel2");

        StudentRole.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        StudentRole.setText("Student");

        StudentID.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        StudentID.setText("TPXXXXXX");

        javax.swing.GroupLayout topUserInfoLayout = new javax.swing.GroupLayout(topUserInfo);
        topUserInfo.setLayout(topUserInfoLayout);
        topUserInfoLayout.setHorizontalGroup(
            topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addGroup(topUserInfoLayout.createSequentialGroup()
                        .addComponent(StudentRole, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        topUserInfoLayout.setVerticalGroup(
            topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topUserInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(topUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topUserInfoLayout.createSequentialGroup()
                        .addComponent(StudentID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StudentRole)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        top.add(topUserInfo, java.awt.BorderLayout.EAST);

        main.add(top, java.awt.BorderLayout.NORTH);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(822, 563));

        lblFilter.setBackground(new java.awt.Color(255, 255, 255));
        lblFilter.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblFilter.setText("Filter");
        lblFilter.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblModule.setBackground(new java.awt.Color(255, 255, 255));
        lblModule.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblModule.setText("Module:");
        lblModule.setPreferredSize(new java.awt.Dimension(90, 24));

        cbModule.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbModule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Module", "Academic Research Study", "Introduction To Business", "Mathematics", "Further Mathematics", "Introduction To Object Oriented Programming", "Introduction To Artificial Intelligence" }));
        cbModule.addActionListener(this::cbModuleActionPerformed);

        lblType.setBackground(new java.awt.Color(255, 255, 255));
        lblType.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblType.setText("Type:");
        lblType.setPreferredSize(new java.awt.Dimension(90, 24));

        cbType.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class Type", "Lecture", "Lab", "Tutorial" }));
        cbType.addActionListener(this::cbTypeActionPerformed);

        lblAvailableClasses.setBackground(new java.awt.Color(255, 255, 255));
        lblAvailableClasses.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblAvailableClasses.setText("Available Classes");
        lblAvailableClasses.setPreferredSize(new java.awt.Dimension(90, 24));

        btnRegisterSelectedClasses.setBackground(new java.awt.Color(204, 255, 204));
        btnRegisterSelectedClasses.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegisterSelectedClasses.setText("Register Selected Class");
        btnRegisterSelectedClasses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegisterSelectedClasses.setBorderPainted(false);
        btnRegisterSelectedClasses.setFocusPainted(false);
        btnRegisterSelectedClasses.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegisterSelectedClasses.addActionListener(this::btnRegisterSelectedClassesActionPerformed);

        spAvailableClassesTable.setBackground(new java.awt.Color(255, 255, 255));

        tblAvailableClasses.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblAvailableClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Class ID", "Name", "Type", "Day", "Time Slot", "Venue", "Capacity", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAvailableClasses.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblAvailableClasses.setGridColor(new java.awt.Color(0, 0, 0));
        tblAvailableClasses.setRowHeight(44);
        tblAvailableClasses.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblAvailableClasses.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblAvailableClasses.setShowGrid(true);
        spAvailableClassesTable.setViewportView(tblAvailableClasses);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(spAvailableClassesTable, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(lblModule, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cbModule, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(lblAvailableClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegisterSelectedClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbModule, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModule, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailableClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterSelectedClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(spAvailableClassesTable, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main.add(content, java.awt.BorderLayout.LINE_END);

        dbBase.add(main, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadHeaderFromSession() {
        String sid = Session.getStudentId();
        sid = (sid == null) ? "" : sid.trim();

        StudentID.setText(!sid.isBlank() ? sid : "TPXXXXXX");
        StudentRole.setText("Student");
    }
    
    private void initCustom() {
        // table model
        tableModel = new javax.swing.table.DefaultTableModel(
                new Object[]{"Class ID","Name","Type","Day","Time Slot","Venue","Capacity","Status"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        tblAvailableClasses.setModel(tableModel);
        tblAvailableClasses.setRowHeight(44);
        tblAvailableClasses.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblAvailableClasses.getTableHeader().setReorderingAllowed(false);
        tblAvailableClasses.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        // column widths
        int[] widths = {100, 160, 70, 75, 110, 70, 70, 70};
        for (int i = 0; i < widths.length; i++) {
            tblAvailableClasses.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
        }
        
        loadRequiredModulesForCurrentStudent();
        
        // cb
        cbModule.removeAllItems();
        cbModule.addItem("-- Select Module --");
        for (String[] r : FilePath.readAll(FilePath.MODULE_FILE)) {
            if (r.length < 2) continue;
            if (r[0].equalsIgnoreCase("moduleID")) continue;
            cbModule.addItem(r[0].trim() + " - " + r[1].trim());
        }
        cbType.removeAllItems();
        cbType.addItem("-- Select Class Type --");
        cbType.addItem("Lecture");
        cbType.addItem("Lab");
        cbType.addItem("Tutorial");

        // data
        loadDataFromFiles();
        applyFilters();

        tblAvailableClasses.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                btnRegisterSelectedClasses.setEnabled(tblAvailableClasses.getSelectedRow() >= 0);
            }
        });
    }
    
    private void styleTableHeader() {
        JTableHeader header = tblAvailableClasses.getTableHeader();

        // backgrounf n text color
        header.setBackground(new Color(166, 199, 155));
        header.setForeground(Color.BLACK);

        // height
        header.setPreferredSize(new Dimension(header.getWidth(), 40));

        // disable column reordering
        header.setReorderingAllowed(false);

        // center alignment text
        DefaultTableCellRenderer renderer =
                (DefaultTableCellRenderer) header.getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
    }
    
    private void styleTableCells() {
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);

        // center columns
        int[] centerCols = {0, 2, 3, 4, 5, 6, 7};
        for (int col : centerCols) {
            tblAvailableClasses.getColumnModel().getColumn(col)
                    .setCellRenderer(center);
        }
    }
    
    private void loadRequiredModulesForCurrentStudent() {
        requiredModuleIds.clear();

        String studentId = Session.getStudentId();
        if (studentId == null || studentId.isBlank()) {
            return;
        }

        StudentData sData = new StudentData();
        Student s = sData.findById(studentId.trim());

        if (s == null || s.getCurrentCourse() == null || s.getCurrentCourse().trim().isEmpty()) {
            return;
        }

        String courseId = s.getCurrentCourse().trim();

        for (String[] r : FilePath.readAll(FilePath.REQUIRED_MODULE_FILE)) {
            if (r.length < 2) continue;
            if (r[0].equalsIgnoreCase("courseID")) continue;

            String cId = r[0].trim();
            String mId = r[1].trim();

            if (cId.equalsIgnoreCase(courseId)) {
                requiredModuleIds.add(mId);
            }
        }
    }

    private void loadDataFromFiles() {
        allRows.clear();
        moduleLectToModule.clear();
        registeredCountByClass.clear();
        registeredStudentsByClass.clear();

        for (String[] r : FilePath.readAll(FilePath.MODULE_LECTURER_FILE)) {
            if (r.length < 3) continue;
            if (r[0].equalsIgnoreCase("modlectID") || r[0].equalsIgnoreCase("moduleLectID")) continue;
            moduleLectToModule.put(r[0].trim(), r[2].trim());
        }

        RegisteredClassData rcData = new RegisteredClassData();
        for (RegisteredClass rc : rcData.readAll()) {
            String classId = rc.getClassID();
            String studentId = rc.getStudentID();

            registeredCountByClass.put(classId, registeredCountByClass.getOrDefault(classId, 0) + 1);

            registeredStudentsByClass
                    .computeIfAbsent(classId, k -> new HashSet<>())
                    .add(studentId);
        }

        ClassData classData = new ClassData();
        List<ClassInfo> classes = classData.readAll();

        String currentStudentId = Session.getStudentId();

        for (ClassInfo c : classes) {
            String classId = c.getClassID();
            String name = c.getName();
            String type = c.getType();
            String day = c.getClassDay();
            String timeSlot = formatTimeSlot(c.getStartTime(), c.getDurationHour());
            String venue = c.getVenue();

            int limit = c.getSizeLimit();
            int used = registeredCountByClass.getOrDefault(classId, 0);

            String capacity = used + "/" + limit;

            // status priority: Registered > Full > Open
            boolean isRegistered = currentStudentId != null
                    && registeredStudentsByClass.getOrDefault(classId, Collections.emptySet())
                    .contains(currentStudentId);

            String status;
            if (isRegistered) status = "Registered";
            else if (used >= limit) status = "Full";
            else status = "Open";

            String moduleId = moduleLectToModule.getOrDefault(c.getModuleLectID(), "");
            
            if (!requiredModuleIds.isEmpty() && !requiredModuleIds.contains(moduleId)) {
                continue;
            }
            
            allRows.add(new String[]{classId, name, type, day, timeSlot, venue, capacity, status, moduleId});
        }
    }

    private void applyFilters() {
        String moduleSel = (String) cbModule.getSelectedItem();
        String typeSel = (String) cbType.getSelectedItem();

        boolean moduleActive = moduleSel != null && !moduleSel.startsWith("--");
        boolean typeActive = typeSel != null && !typeSel.startsWith("--");

        String selectedModuleId = "";
        if (moduleActive) {
            // "MATHS - Mathematics" -> "MATHS"
            selectedModuleId = moduleSel.split(" - ")[0].trim();
        }
        
        tableModel.setRowCount(0);

        for (String[] r : allRows) {
            String rowType = r[2];
            String rowModuleId = r[8];

            if (typeActive && !rowType.equalsIgnoreCase(typeSel)) continue;
            if (moduleActive && !rowModuleId.equalsIgnoreCase(selectedModuleId)) continue;
            if ("Registered".equalsIgnoreCase(r[7])) continue;
            // add only visible columns to table
            tableModel.addRow(new Object[]{r[0], r[1], r[2], r[3], r[4], r[5], r[6], r[7]});
        }

        if (tblAvailableClasses.getSelectedRowCount() > 0) {
            tblAvailableClasses.clearSelection();
        }
    }
    
    private String formatTimeSlot(String startTimeHHmm, double durationHour) {
        try {
            DateTimeFormatter inFmt = DateTimeFormatter.ofPattern("HHmm");
            DateTimeFormatter outFmt = DateTimeFormatter.ofPattern("HH.mm");

            LocalTime start = LocalTime.parse(startTimeHHmm, inFmt);
            int minutes = (int) Math.round(durationHour * 60.0);
            LocalTime end = start.plusMinutes(minutes);

            return start.format(outFmt) + " - " + end.format(outFmt);
        } catch (Exception e) {
            // fallback if data is weird
            return startTimeHHmm;
        }
    }
    
    private String generateNextRegisteredClassId() {
        RegisteredClassData rcData = new RegisteredClassData();
        int max = 0;

        for (RegisteredClass rc : rcData.readAll()) {
            String id = rc.getRegisteredClassID(); // e.g. RC00001
            if (id == null) continue;

            id = id.trim().toUpperCase();
            if (!id.startsWith("RC")) continue;

            // extract digits
            String numStr = id.substring(2).replaceAll("[^0-9]", "");
            if (numStr.isEmpty()) continue;

            try {
                int n = Integer.parseInt(numStr);
                if (n > max) max = n;
            } catch (NumberFormatException ignored) {}
        }

        int next = max + 1;
        return String.format("RC%05d", next);
    }
    
    private List<ClassInfo> getSelectedClassesFromTable() {
        int[] rows = tblAvailableClasses.getSelectedRows();
        if (rows == null || rows.length == 0) return Collections.emptyList();

        List<ClassInfo> selected = new ArrayList<>();
        ClassData cd = new ClassData();

        for (int r : rows) {
            String classId = tblAvailableClasses.getValueAt(r, 0).toString().trim();
            ClassInfo c = cd.findById(classId);
            if (c != null) selected.add(c);
        }
        return selected;
    }
    
    private String classTypeBucket(String type) {
        if (type == null) return "";
        type = type.trim().toLowerCase();

        if (type.contains("lecture")) return "LECTURE";
        if (type.contains("lab")) return "LAB_TUTORIAL";
        if (type.contains("tutorial")) return "LAB_TUTORIAL";

        return "OTHER";
    }
    
    private String getModuleIdByClassId(String classId) {
        for (String[] r : allRows) {
            if (r.length >= 9 && r[0].equalsIgnoreCase(classId)) {
                return r[8].trim(); // moduleId
            }
        }
        return "";
    }
    
    private boolean validateTwoClassSelection(List<ClassInfo> selected) {

        if (selected == null || selected.size() != 2) {
            JOptionPane.showMessageDialog(this,
                    "You must choose exactly TWO classes:\n"
                  + "✔ 1 Lecture class\n"
                  + "✔ 1 Lab OR Tutorial class",
                    "Selection required",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        ClassInfo c1 = selected.get(0);
        ClassInfo c2 = selected.get(1);

        String moduleA = getModuleIdByClassId(c1.getClassID());
        String moduleB = getModuleIdByClassId(c2.getClassID());

        if (moduleA.isEmpty() || moduleB.isEmpty() || !moduleA.equalsIgnoreCase(moduleB)) {
            JOptionPane.showMessageDialog(this,
                    "Both selected classes must be from the SAME module.",
                    "Invalid selection",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        String bucket1 = classTypeBucket(c1.getType());
        String bucket2 = classTypeBucket(c2.getType());

        boolean hasLecture = bucket1.equals("LECTURE") || bucket2.equals("LECTURE");
        boolean hasLabTut = bucket1.equals("LAB_TUTORIAL") || bucket2.equals("LAB_TUTORIAL");

        if (!hasLecture || !hasLabTut) {
            JOptionPane.showMessageDialog(this,
                    "Invalid combination.\n\n"
                  + "You must select:\n"
                  + "✅ ONE Lecture\n"
                  + "✅ ONE Lab OR Tutorial (only one of these)",
                    "Invalid selection",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (bucket1.equals(bucket2)) {
            JOptionPane.showMessageDialog(this,
                    "You selected 2 classes from the same category.\n"
                  + "Please select ONE Lecture + ONE Lab/Tutorial.",
                    "Invalid selection",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }
    
    private void btnNavDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavDashboardActionPerformed
        new StudentDashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavDashboardActionPerformed

    private void btnNavMyClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavMyClassesActionPerformed
        new StudentMyClasses().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavMyClassesActionPerformed

    private void btnNavAssessmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavAssessmentsActionPerformed
        new StudentAssessments().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavAssessmentsActionPerformed

    private void btnNavGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavGradesActionPerformed
        new StudentGrades().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavGradesActionPerformed

    private void btnNavFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavFeedbackActionPerformed
        new StudentFeedback().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavFeedbackActionPerformed

    private void btnNavProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavProfileActionPerformed
        new StudentProfile().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavProfileActionPerformed

    private void cbModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModuleActionPerformed
        applyFilters();
    }//GEN-LAST:event_cbModuleActionPerformed

    private void cbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeActionPerformed
        applyFilters();
    }//GEN-LAST:event_cbTypeActionPerformed

    private void btnRegisterSelectedClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSelectedClassesActionPerformed
        String studentId = Session.getStudentId();
        if (studentId == null || studentId.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Session student not set.\nSet Session.setStudentId(...) before using this page.",
                    "Session Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        studentId = studentId.trim();

        // get selected classes (2 rows)
        List<ClassInfo> selectedClasses = getSelectedClassesFromTable();

        // validate rule (1 lecture + 1 lab/tutorial, same module)
        if (!validateTwoClassSelection(selectedClasses)) {
            return;
        }

        RegisteredClassData rcData = new RegisteredClassData();
        ClassData classData = new ClassData();

        // confirm
        String classA = selectedClasses.get(0).getClassID();
        String classB = selectedClasses.get(1).getClassID();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Register these classes?\n" + classA + " and " + classB,
                "Confirm Registration",
                JOptionPane.YES_NO_OPTION
        );
        if (confirm != JOptionPane.YES_OPTION) return;

        // capacity + duplicate checks for BOTH
        for (ClassInfo cls : selectedClasses) {
            String classId = cls.getClassID();

            if (rcData.exists(studentId, classId)) {
                JOptionPane.showMessageDialog(this,
                        "You already registered class: " + classId,
                        "Duplicate", JOptionPane.WARNING_MESSAGE);
                return;
            }

            ClassInfo fullInfo = classData.findById(classId);
            if (fullInfo == null) {
                JOptionPane.showMessageDialog(this,
                        "Class not found in class.txt: " + classId,
                        "Data Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int used = rcData.countByClassId(classId);
            int limit = fullInfo.getSizeLimit();
            if (used >= limit) {
                JOptionPane.showMessageDialog(this,
                        "Class is full: " + classId + " (" + used + "/" + limit + ")",
                        "Full", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        // append both registrations
        String date = LocalDate.now().format(DateTimeFormatter.ISO_DATE);

        for (ClassInfo cls : selectedClasses) {
            String rcId = generateNextRegisteredClassId(); // generates new ID each time
            RegisteredClass newRc = new RegisteredClass(rcId, cls.getClassID(), studentId, date);

            boolean ok = rcData.append(newRc);
            if (!ok) {
                JOptionPane.showMessageDialog(this,
                        "Failed to register class: " + cls.getClassID(),
                        "Write Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Registered successfully (Lecture + Lab/Tutorial).");

        loadDataFromFiles();
        applyFilters();
        
        // create moduleResult row if not exist
        String moduleId = getModuleIdByClassId(selectedClasses.get(0).getClassID());

        if (moduleId != null && !moduleId.isBlank()) {
            ModuleResultData mrd = new ModuleResultData();

            if (!mrd.existsStudentModule(studentId, moduleId)) {
                String mrId = mrd.generateNextModuleResultId();

                ModuleResult newMr = new ModuleResult(mrId, studentId, moduleId, 0.0, 0.0, 0.0, null);

                boolean okMr = mrd.append(newMr);
                if (!okMr) {
                    JOptionPane.showMessageDialog(this,
                            "Registered classes, but failed to create ModuleResult row.\nPlease check moduleResult.txt path.",
                            "ModuleResult Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnRegisterSelectedClassesActionPerformed

    private void btnNavLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavLogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
                "Logging out?", 
                "Confirmation", 
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new AFS_LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnNavLogoutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StudentID;
    private javax.swing.JLabel StudentProfilePic;
    private javax.swing.JLabel StudentRole;
    private javax.swing.JButton btnNavAssessments;
    private javax.swing.JButton btnNavDashboard;
    private javax.swing.JButton btnNavFeedback;
    private javax.swing.JButton btnNavGrades;
    private javax.swing.JButton btnNavLogout;
    private javax.swing.JButton btnNavMyClasses;
    private javax.swing.JButton btnNavProfile;
    private javax.swing.JButton btnRegisterSelectedClasses;
    private javax.swing.JComboBox<String> cbModule;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JPanel content;
    private javax.swing.JPanel dbBase;
    private javax.swing.JPanel gap1;
    private javax.swing.JPanel gap2;
    private javax.swing.JPanel gap3;
    private javax.swing.JLabel lblAFSlogo;
    private javax.swing.JLabel lblAvailableClasses;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblModule;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnlAFSlogo;
    private javax.swing.JPanel pnlNavAssessments;
    private javax.swing.JPanel pnlNavDashboard;
    private javax.swing.JPanel pnlNavFeedback;
    private javax.swing.JPanel pnlNavGrades;
    private javax.swing.JPanel pnlNavLogout;
    private javax.swing.JPanel pnlNavMyClasses;
    private javax.swing.JPanel pnlNavProfile;
    private javax.swing.JPanel sidebar;
    private javax.swing.JScrollPane spAvailableClassesTable;
    private javax.swing.JTable tblAvailableClasses;
    private javax.swing.JPanel top;
    private javax.swing.JPanel topTitle;
    private javax.swing.JPanel topUserInfo;
    private javax.swing.JLabel txtRegisterNewClasses;
    // End of variables declaration//GEN-END:variables
}
