/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Classes.AcademicLeader;
import Classes.AdminTask;
import Classes.Faculty;
import Classes.Student;
import static Admin.Admin_11AcadLeadRegister.cmbFaculty;
import Classes.Session;
import Login.AFS_LoginPage;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author aqilahazis
 */
public class Admin_10AcadLeadMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_10AcadLeadMain.class.getName());

    /**
     * Creates new form Admin_10AcadLeadMain
     */
    public Admin_10AcadLeadMain() {
        initComponents();
        
        JTableHeader header = tblAcadlead.getTableHeader();
        header.setPreferredSize(new Dimension(100, 30)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        userspace = new javax.swing.JLayeredPane();
        lblDasboardTitle = new javax.swing.JLabel();
        lblQuickaction = new javax.swing.JLabel();
        btnAcadleadreg = new javax.swing.JButton();
        paneRegisterClass = new javax.swing.JScrollPane();
        tblAcadlead = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lblPfp = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        side = new javax.swing.JLayeredPane();
        logo = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnLect = new javax.swing.JButton();
        btnClass = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAcadlead = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(775, 643));

        javax.swing.GroupLayout userspaceLayout = new javax.swing.GroupLayout(userspace);
        userspace.setLayout(userspaceLayout);
        userspaceLayout.setHorizontalGroup(
            userspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        userspaceLayout.setVerticalGroup(
            userspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        lblDasboardTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblDasboardTitle.setText("Academic Leader");

        lblQuickaction.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblQuickaction.setText("Academic Leader List");

        btnAcadleadreg.setBackground(new java.awt.Color(232, 247, 246));
        btnAcadleadreg.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnAcadleadreg.setText("New Academic Leader Registration");
        btnAcadleadreg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAcadleadreg.setOpaque(true);
        btnAcadleadreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcadleadregActionPerformed(evt);
            }
        });

        tblAcadlead.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Academic Leader Name", "ID", "Faculty In Charge", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAcadlead.setGridColor(new java.awt.Color(102, 102, 102));
        tblAcadlead.setRowHeight(45);
        tblAcadlead.setSelectionBackground(new java.awt.Color(241, 241, 241));
        tblAcadlead.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblAcadlead.getTableHeader().setReorderingAllowed(false);
        tblAcadlead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAcadleadMouseClicked(evt);
            }
        });
        paneRegisterClass.setViewportView(tblAcadlead);
        if (tblAcadlead.getColumnModel().getColumnCount() > 0) {
            tblAcadlead.getColumnModel().getColumn(0).setResizable(false);
            tblAcadlead.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblAcadlead.getColumnModel().getColumn(1).setResizable(false);
            tblAcadlead.getColumnModel().getColumn(2).setResizable(false);
            tblAcadlead.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblAcadlead.getColumnModel().getColumn(3).setResizable(false);
        }

        txtSearch.setForeground(new java.awt.Color(153, 153, 153));
        txtSearch.setText("Search name or ID");
        txtSearch.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        lblPfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pfp.png"))); // NOI18N

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblUsername.setText("username");

        lblRole.setText("role");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblQuickaction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblPfp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUsername)
                                .addComponent(lblRole)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(userspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(433, 433, 433))
                        .addComponent(btnAcadleadreg, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(lblDasboardTitle)
                    .addContainerGap(633, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(paneRegisterClass, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblPfp))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnAcadleadreg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuickaction))
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(lblDasboardTitle)
                    .addContainerGap(577, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(202, 202, 202)
                    .addComponent(paneRegisterClass, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );

        side.setBackground(new java.awt.Color(24, 29, 49));
        side.setOpaque(true);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assessment-feedback-system-high-resolution-logo-transparent-3 (2).png"))); // NOI18N

        btnDashboard.setBackground(new java.awt.Color(24, 29, 49));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logologlo.png"))); // NOI18N
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard.setBorderPainted(false);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setOpaque(true);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnStudent.setBackground(new java.awt.Color(24, 29, 49));
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 2.png"))); // NOI18N
        btnStudent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnStudent.setOpaque(true);
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnLect.setBackground(new java.awt.Color(24, 29, 49));
        btnLect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy.png"))); // NOI18N
        btnLect.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLect.setOpaque(true);
        btnLect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLectActionPerformed(evt);
            }
        });

        btnClass.setBackground(new java.awt.Color(24, 29, 49));
        btnClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 4.png"))); // NOI18N
        btnClass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClass.setOpaque(true);
        btnClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassActionPerformed(evt);
            }
        });

        btnSettings.setBackground(new java.awt.Color(24, 29, 49));
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 5.png"))); // NOI18N
        btnSettings.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSettings.setOpaque(true);
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(24, 29, 49));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 6.png"))); // NOI18N
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout.setOpaque(true);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAcadlead.setBackground(new java.awt.Color(24, 29, 49));
        btnAcadlead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logologlo copy 3.png"))); // NOI18N
        btnAcadlead.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAcadlead.setOpaque(true);
        btnAcadlead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcadleadActionPerformed(evt);
            }
        });

        side.setLayer(logo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side.setLayer(btnDashboard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side.setLayer(btnStudent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side.setLayer(btnLect, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side.setLayer(btnClass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side.setLayer(btnSettings, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side.setLayer(btnLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side.setLayer(btnAcadlead, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sideLayout = new javax.swing.GroupLayout(side);
        side.setLayout(sideLayout);
        sideLayout.setHorizontalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStudent)
                            .addComponent(btnLect)
                            .addComponent(btnLogout)
                            .addComponent(btnSettings)
                            .addComponent(btnClass)
                            .addComponent(btnAcadlead)))
                    .addGroup(sideLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDashboard)
                            .addComponent(logo))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        sideLayout.setVerticalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logo)
                .addGap(39, 39, 39)
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcadlead, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSettings)
                .addGap(55, 55, 55)
                .addComponent(btnLogout)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(side, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(side))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        //Assignment.Admin_2StudentMain.show();
        new Admin_2StudentMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnLectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLectActionPerformed
        new Admin_5LecturerMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLectActionPerformed

    private void btnClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassActionPerformed
        new Admin_8AssignClass().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClassActionPerformed

    private void btnAcadleadregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcadleadregActionPerformed
        new Admin_11AcadLeadRegister().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcadleadregActionPerformed

    private void tblAcadleadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAcadleadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAcadleadMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        String searchText = txtSearch.getText().toLowerCase();
        List<String> containLines = new ArrayList<>();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //            DefaultTableModel dtm = (DefaultTableModel) tableStudent.getModel();
            //            dtm.setRowCount(0);
            AdminTask task = new AdminTask();
            List<String> data = task.readtxt("academicLeader.txt");
            AcademicLeader acadlead = new AcademicLeader();
            acadlead.searchfunc(data, searchText, containLines, tblAcadlead);
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        tblAcadlead.getTableHeader().setBackground(Color.decode("#d9e1ec"));
        
        AdminTask.initUsernameRole(Session.getUsername(), Session.getRole(), lblUsername, lblRole);
        AdminTask task = new AdminTask();
        List<String> data = AdminTask.readtxt("academicLeader.txt");
        task.addRowtoTable(tblAcadlead, data, 8);
        tblAcadlead.getColumnModel().setColumnMargin(10);
//        admin = new User();
//        AdminTask.initUsernameRole(admin.getUsername(), admin.getRole(), lblUsername, lblRole);
        
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                String rowID = tblAcadlead.getModel().getValueAt(row, 1).toString();
                //System.out.println(rowID);
                
                //student
                AcademicLeader acadlead = new AcademicLeader();
                acadlead.setAcadLeadID(rowID);
                
                Admin_12AcadLeadEdit editPage = new Admin_12AcadLeadEdit();

                acadlead.editALInit(
                    editPage.getFacultyCombo(),
                    editPage.getLblID(),
                    editPage.getTxtUsername(),
                    editPage.getTxtFullName(),
                    editPage.getTxtPw()
                );
                
                //open student edit page
                //Assignment.Admin_4StudentEdit.show();
                //Faculty.addfacultytoCmb(cmbFaculty);
                editPage.setVisible(true);               
                //Assignment.Admin_2StudentMain.hide();
                Admin_10AcadLeadMain.this.dispose();
            }

            @Override
            public void onDelete(int row) {
                int result = JOptionPane.showConfirmDialog(null, "Delete academic leader data?", "Confirmation", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION){
                    String rowID = tblAcadlead.getModel().getValueAt(row, 1).toString();
                    
                    AcademicLeader acadlead = new AcademicLeader();
                    acadlead.deleteAL(rowID);
                    
                    JOptionPane.showMessageDialog(null, "Academic leader data has been successfully deleted");
                } else {
                    JOptionPane.showMessageDialog(null, "Deletion cancelled");
                }
                List<String> data = task.readtxt("academicLeader.txt");
                task.addRowtoTable(tblAcadlead, data, 8);
                
                Admin_10AcadLeadMain mainPage = new Admin_10AcadLeadMain();
                mainPage.setVisible(true);
                Admin_10AcadLeadMain.this.dispose();
            }
        };
        tblAcadlead.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRender());
        tblAcadlead.getColumnModel().getColumn(3).setCellEditor(new TableActionCellEditor(event));
    }//GEN-LAST:event_formComponentShown

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        new Admin_1dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnAcadleadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcadleadActionPerformed

    }//GEN-LAST:event_btnAcadleadActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        new Admin_13Settings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
                "Logging out?", 
                "Confirmation", 
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new AFS_LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        txtSearch.setText("");
        txtSearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtSearchFocusGained

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcadlead;
    private javax.swing.JButton btnAcadleadreg;
    private javax.swing.JButton btnClass;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLect;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnStudent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDasboardTitle;
    private javax.swing.JLabel lblPfp;
    private javax.swing.JLabel lblQuickaction;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane paneRegisterClass;
    private javax.swing.JLayeredPane side;
    public static javax.swing.JTable tblAcadlead;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLayeredPane userspace;
    // End of variables declaration//GEN-END:variables
}
