/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import static Admin.Admin_4StudentEdit.cmbCourse;
import static Admin.Admin_4StudentEdit.lblID;
import static Admin.Admin_4StudentEdit.txtEmail;
import static Admin.Admin_4StudentEdit.txtFullName;
import static Admin.Admin_4StudentEdit.txtPhone;
import static Admin.Admin_4StudentEdit.txtPw;
import static Admin.Admin_4StudentEdit.txtUsername;
import static Admin.Admin_5LecturerMain.tableLecturer;
import Classes.AdminTask;
import Classes.Lecturer;
import Login.AFS_LoginPage;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author aqilahazis
 */
public class Admin_7LecturerEdit extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_7LecturerEdit.class.getName());

    /**
     * Creates new form Admin_7LecturerEdit
     */
    public Admin_7LecturerEdit() {
        initComponents();
    }
    
    public JComboBox getTitleCombo() {
        return cmbTitle;
    }
    
    public JComboBox getAcadLeadCombo() {
        return cmbacadlead;
    }

    public JLabel getLblID() {
        return lblID;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public JTextField getTxtFullName() {
        return txtFullName;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtPhone() {
        return txtPhone;
    }

    public JTextField getTxtPw() {
        return txtPw;
    }
    
    public JTextField getTxtAcadQual() {
        return txtacadQual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        side3 = new javax.swing.JLayeredPane();
        logo3 = new javax.swing.JLabel();
        btnDashboard3 = new javax.swing.JButton();
        btnStudent3 = new javax.swing.JButton();
        btnLect3 = new javax.swing.JButton();
        btnClass3 = new javax.swing.JButton();
        btnSettings3 = new javax.swing.JButton();
        btnLogout3 = new javax.swing.JButton();
        btnAcadlead3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDasboardTitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPw = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbacadlead = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbTitle = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtacadQual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        side3.setBackground(new java.awt.Color(24, 29, 49));
        side3.setOpaque(true);

        logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assessment-feedback-system-high-resolution-logo-transparent-3 (2).png"))); // NOI18N

        btnDashboard3.setBackground(new java.awt.Color(24, 29, 49));
        btnDashboard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logologlo.png"))); // NOI18N
        btnDashboard3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard3.setBorderPainted(false);
        btnDashboard3.setFocusPainted(false);
        btnDashboard3.setOpaque(true);
        btnDashboard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboard3ActionPerformed(evt);
            }
        });

        btnStudent3.setBackground(new java.awt.Color(24, 29, 49));
        btnStudent3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 2.png"))); // NOI18N
        btnStudent3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnStudent3.setOpaque(true);
        btnStudent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudent3ActionPerformed(evt);
            }
        });

        btnLect3.setBackground(new java.awt.Color(24, 29, 49));
        btnLect3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logologlo copy.png"))); // NOI18N
        btnLect3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLect3.setOpaque(true);
        btnLect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLect3ActionPerformed(evt);
            }
        });

        btnClass3.setBackground(new java.awt.Color(24, 29, 49));
        btnClass3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 4.png"))); // NOI18N
        btnClass3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClass3.setOpaque(true);
        btnClass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClass3ActionPerformed(evt);
            }
        });

        btnSettings3.setBackground(new java.awt.Color(24, 29, 49));
        btnSettings3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 5.png"))); // NOI18N
        btnSettings3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSettings3.setOpaque(true);
        btnSettings3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettings3ActionPerformed(evt);
            }
        });

        btnLogout3.setBackground(new java.awt.Color(24, 29, 49));
        btnLogout3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 6.png"))); // NOI18N
        btnLogout3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout3.setOpaque(true);
        btnLogout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout3ActionPerformed(evt);
            }
        });

        btnAcadlead3.setBackground(new java.awt.Color(24, 29, 49));
        btnAcadlead3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 3.png"))); // NOI18N
        btnAcadlead3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAcadlead3.setOpaque(true);
        btnAcadlead3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcadlead3ActionPerformed(evt);
            }
        });

        side3.setLayer(logo3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnDashboard3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnStudent3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnLect3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnClass3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnSettings3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnLogout3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnAcadlead3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout side3Layout = new javax.swing.GroupLayout(side3);
        side3.setLayout(side3Layout);
        side3Layout.setHorizontalGroup(
            side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side3Layout.createSequentialGroup()
                .addGroup(side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(side3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLect3)
                            .addComponent(btnLogout3)
                            .addComponent(btnSettings3)
                            .addComponent(btnClass3)
                            .addComponent(btnAcadlead3)
                            .addComponent(btnStudent3)))
                    .addGroup(side3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDashboard3)
                            .addComponent(logo3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        side3Layout.setVerticalGroup(
            side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logo3)
                .addGap(39, 39, 39)
                .addComponent(btnDashboard3)
                .addGap(12, 12, 12)
                .addComponent(btnStudent3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLect3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcadlead3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClass3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSettings3)
                .addGap(55, 55, 55)
                .addComponent(btnLogout3)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side3)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(775, 643));

        lblDasboardTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblDasboardTitle.setText("Lecturer Registration");

        txtUsername.setBackground(new java.awt.Color(227, 227, 227));
        txtUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtUsername.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtUsername.setEnabled(false);

        txtPw.setBackground(new java.awt.Color(227, 227, 227));
        txtPw.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtPw.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtPw.setEnabled(false);

        txtFullName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        txtPhone.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        txtEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        jLabel1.setText("Username*");

        jLabel2.setText("Password*");

        jLabel3.setText("Full Name*");

        jLabel5.setText("Email*");

        jLabel6.setText("Phone Number*");

        btnSave.setBackground(new java.awt.Color(217, 225, 236));
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSave.setOpaque(true);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(217, 225, 236));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCancel.setOpaque(true);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        lblID.setText("ID: ");

        jLabel10.setText("Academic Leader*");

        cmbacadlead.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Title");

        cmbTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr.", "Ts.", "Ts. Dr.", "Prof", "Prof. Dr.", "Mr.", "Ms." }));
        cmbTitle.setSelectedIndex(-1);
        cmbTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Academic Qualification ");

        txtacadQual.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtacadQual.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblDasboardTitle)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFullName)
                            .addComponent(txtEmail)
                            .addComponent(cmbTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(lblID)
                                    .addComponent(jLabel7)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtacadQual, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cmbacadlead, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(210, 210, 210))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblDasboardTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbacadlead, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtacadQual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String ID = lblID.getText().substring(lblID.getText().indexOf(' ') +1);
        String username = txtUsername.getText();
        String name = txtFullName.getText();
        String email = txtEmail.getText().toLowerCase();
        String phoneNo = txtPhone.getText();
        String title = (String) cmbTitle.getSelectedItem();
        String acadlead = (String) cmbacadlead.getSelectedItem();
        String acadqual = txtacadQual.getText();

        Lecturer lect = new Lecturer();
        int check = lect.registerLecturer(ID, username, name, title, email, phoneNo, acadqual, acadlead);

        if (check == 1){
            // message box pop up
            JOptionPane.showMessageDialog(this, "Student data has been recorded",
                "Information",
                JOptionPane.INFORMATION_MESSAGE);
            //pergi page 2 balik
            AdminTask task = new AdminTask();
            List<String> data = task.readtxt("lecturer.txt");
            task.addRowtoTable(tableLecturer, data, 1);

            new Admin_5LecturerMain().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Student data isn't recorded. Try again.",
                "Information",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new Admin_5LecturerMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDashboard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard3ActionPerformed
        new Admin_1dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboard3ActionPerformed

    private void btnStudent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudent3ActionPerformed
        //Assignment.Admin_2StudentMain.show();
        new Admin_2StudentMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudent3ActionPerformed

    private void btnLect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLect3ActionPerformed

    }//GEN-LAST:event_btnLect3ActionPerformed

    private void btnClass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClass3ActionPerformed
        new Admin_8AssignClass().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClass3ActionPerformed

    private void btnSettings3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings3ActionPerformed
        new Admin_13Settings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSettings3ActionPerformed

    private void btnLogout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout3ActionPerformed
        int result = JOptionPane.showConfirmDialog(null,
            "Logging out?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new AFS_LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogout3ActionPerformed

    private void btnAcadlead3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcadlead3ActionPerformed
        new Admin_10AcadLeadMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcadlead3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_7LecturerEdit().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcadlead3;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClass3;
    private javax.swing.JButton btnDashboard3;
    private javax.swing.JButton btnLect3;
    private javax.swing.JButton btnLogout3;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSettings3;
    private javax.swing.JButton btnStudent3;
    public static javax.swing.JComboBox<String> cmbTitle;
    public static javax.swing.JComboBox<String> cmbacadlead;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDasboardTitle;
    public static javax.swing.JLabel lblID;
    private javax.swing.JLabel logo3;
    private javax.swing.JLayeredPane side3;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtFullName;
    public static javax.swing.JTextField txtPhone;
    public static javax.swing.JTextField txtPw;
    public static javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtacadQual;
    // End of variables declaration//GEN-END:variables
}
