/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import static Admin.Admin_2StudentMain.tableStudent;
import Classes.AdminTask;
import Classes.Student;
import Classes.User;
import Login.AFS_LoginPage;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author aqilahazis
 */
public class Admin_3StudentRegister extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_3StudentRegister.class.getName());

    /**
     * Creates new form StudentRegister
     */
    public Admin_3StudentRegister() {
        initComponents();
        
    }
    
    public void resetForm() {
        cmbCourse.removeAllItems();
        txtFullName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        cmbCourse.setSelectedIndex(-1);
        String newID = "";
        Student student = new Student();
        String lastID = student.getlastIDnumber();
        int numberID = Integer.parseInt(lastID.substring(2));
        numberID += 1;
        if(String.valueOf(numberID).length() != 6){
            newID = String.format("%" + 6 + "s", String.valueOf(numberID)).replace(' ', '0');
        }
        newID = "TP" + newID;
        
        txtUsername.setText(newID.toLowerCase());
        txtPw.setText("12345678");
        txtID.setText(newID);
        
        //addcourse in combo box
        AdminTask task = new AdminTask();
        task.addCoursetoCmb(cmbCourse);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        side8 = new javax.swing.JLayeredPane();
        logo8 = new javax.swing.JLabel();
        btnDashboard8 = new javax.swing.JButton();
        btnStudent8 = new javax.swing.JButton();
        btnLect8 = new javax.swing.JButton();
        btnClass8 = new javax.swing.JButton();
        btnSettings8 = new javax.swing.JButton();
        btnLogout8 = new javax.swing.JButton();
        btnAcadlead8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDasboardTitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPw = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        side8.setBackground(new java.awt.Color(24, 29, 49));
        side8.setOpaque(true);

        logo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assessment-feedback-system-high-resolution-logo-transparent-3 (2).png"))); // NOI18N

        btnDashboard8.setBackground(new java.awt.Color(24, 29, 49));
        btnDashboard8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logologlo.png"))); // NOI18N
        btnDashboard8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard8.setBorderPainted(false);
        btnDashboard8.setFocusPainted(false);
        btnDashboard8.setOpaque(true);
        btnDashboard8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboard8ActionPerformed(evt);
            }
        });

        btnStudent8.setBackground(new java.awt.Color(24, 29, 49));
        btnStudent8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logologlo copy 2.png"))); // NOI18N
        btnStudent8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnStudent8.setOpaque(true);
        btnStudent8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudent8ActionPerformed(evt);
            }
        });

        btnLect8.setBackground(new java.awt.Color(24, 29, 49));
        btnLect8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy.png"))); // NOI18N
        btnLect8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLect8.setOpaque(true);
        btnLect8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLect8ActionPerformed(evt);
            }
        });

        btnClass8.setBackground(new java.awt.Color(24, 29, 49));
        btnClass8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 4.png"))); // NOI18N
        btnClass8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClass8.setOpaque(true);
        btnClass8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClass8ActionPerformed(evt);
            }
        });

        btnSettings8.setBackground(new java.awt.Color(24, 29, 49));
        btnSettings8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 5.png"))); // NOI18N
        btnSettings8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSettings8.setOpaque(true);
        btnSettings8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettings8ActionPerformed(evt);
            }
        });

        btnLogout8.setBackground(new java.awt.Color(24, 29, 49));
        btnLogout8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 6.png"))); // NOI18N
        btnLogout8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout8.setOpaque(true);
        btnLogout8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout8ActionPerformed(evt);
            }
        });

        btnAcadlead8.setBackground(new java.awt.Color(24, 29, 49));
        btnAcadlead8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 3.png"))); // NOI18N
        btnAcadlead8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAcadlead8.setOpaque(true);
        btnAcadlead8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcadlead8ActionPerformed(evt);
            }
        });

        side8.setLayer(logo8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side8.setLayer(btnDashboard8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side8.setLayer(btnStudent8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side8.setLayer(btnLect8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side8.setLayer(btnClass8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side8.setLayer(btnSettings8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side8.setLayer(btnLogout8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side8.setLayer(btnAcadlead8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout side8Layout = new javax.swing.GroupLayout(side8);
        side8.setLayout(side8Layout);
        side8Layout.setHorizontalGroup(
            side8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side8Layout.createSequentialGroup()
                .addGroup(side8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(side8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(side8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLect8)
                            .addComponent(btnLogout8)
                            .addComponent(btnSettings8)
                            .addComponent(btnClass8)
                            .addComponent(btnAcadlead8)))
                    .addGroup(side8Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(side8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDashboard8)
                            .addComponent(logo8)
                            .addComponent(btnStudent8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        side8Layout.setVerticalGroup(
            side8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logo8)
                .addGap(39, 39, 39)
                .addComponent(btnDashboard8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStudent8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLect8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcadlead8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClass8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSettings8)
                .addGap(55, 55, 55)
                .addComponent(btnLogout8)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side8)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side8)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(775, 643));

        lblDasboardTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblDasboardTitle.setText("Student Registration");

        txtUsername.setBackground(new java.awt.Color(227, 227, 227));
        txtUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtUsername.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtUsername.setEnabled(false);
        txtUsername.setOpaque(true);

        txtPw.setBackground(new java.awt.Color(227, 227, 227));
        txtPw.setText("12345678");
        txtPw.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtPw.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtPw.setEnabled(false);
        txtPw.setOpaque(true);

        txtFullName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtFullName.setOpaque(true);

        txtID.setBackground(new java.awt.Color(227, 227, 227));
        txtID.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtID.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtID.setEnabled(false);
        txtID.setOpaque(true);

        txtPhone.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtPhone.setOpaque(true);

        txtEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtEmail.setOpaque(true);

        jLabel1.setText("Username*");

        jLabel2.setText("Password*");

        jLabel3.setText("Full Name*");

        jLabel4.setText("StudentID*");

        jLabel5.setText("Email*");

        jLabel6.setText("Phone Number*");

        jLabel7.setText("Selected Course*");

        cmbCourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSave.setBackground(new java.awt.Color(217, 225, 236));
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSave.setOpaque(true);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(217, 225, 236));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCancel.setOpaque(true);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(315, 315, 315))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtID)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(341, 341, 341))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(50, 50, 50)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhone)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2)
                                            .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblDasboardTitle)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblDasboardTitle)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String username = txtUsername.getText();       
        String password = txtPw.getText();
        String ID = txtID.getText();
        String name = txtFullName.getText();
        String email = txtEmail.getText().toLowerCase();
        String phoneNo = txtPhone.getText();
        String course = (String) cmbCourse.getSelectedItem();
        
        try {
            Student student = new Student();
            int check = student.registerStudent(ID, username, name, email, phoneNo, course);
            
            User user = new User();
            user.createUser(username, password, "Student");
            
            if (check == 1){
                // message box pop up
                JOptionPane.showMessageDialog(this, "Student data has been recorded", 
                                                "Information", 
                                                JOptionPane.INFORMATION_MESSAGE);
                resetForm();
                List<String> data = AdminTask.readtxt("student.txt");
                AdminTask.addRowtoTable(tableStudent, data, 1);
            } else {
                JOptionPane.showMessageDialog(this, "Student data isn't recorded. Try again.", 
                                                "Information", 
                                                JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            // Code to handle the exception if it occurs// message box pop up
            JOptionPane.showMessageDialog(this, "Student data couldn't be recorded. Try again.", 
                                            "Information", 
                                            JOptionPane.INFORMATION_MESSAGE);
            
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        resetForm();
        new Admin_2StudentMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        //resetForm();
    }//GEN-LAST:event_formWindowStateChanged

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        resetForm();
    }//GEN-LAST:event_formComponentShown

    private void btnDashboard8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard8ActionPerformed
        Admin_1dashboard Admin_1dashboardpage = new Admin_1dashboard();
        Admin_1dashboardpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboard8ActionPerformed

    private void btnStudent8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudent8ActionPerformed
        Admin_2StudentMain Admin_2StudentMainpage = new Admin_2StudentMain();
        Admin_2StudentMainpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudent8ActionPerformed

    private void btnLect8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLect8ActionPerformed
        Admin_5LecturerMain Admin_5LecturerMainpage = new Admin_5LecturerMain();
        Admin_5LecturerMainpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLect8ActionPerformed

    private void btnClass8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClass8ActionPerformed
        Admin_8AssignClass Admin_8AssignClasspage = new Admin_8AssignClass();
        Admin_8AssignClasspage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClass8ActionPerformed

    private void btnSettings8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings8ActionPerformed
        Admin_13Settings Admin_13Settingspage = new Admin_13Settings();
        Admin_13Settingspage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSettings8ActionPerformed

    private void btnLogout8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout8ActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
        "Logging out?", 
        "Confirmation", 
        JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new AFS_LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogout8ActionPerformed

    private void btnAcadlead8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcadlead8ActionPerformed
        Admin_10AcadLeadMain Admin_10AcadLeadMainpage = new Admin_10AcadLeadMain();
        Admin_10AcadLeadMainpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcadlead8ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcadlead8;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClass8;
    private javax.swing.JButton btnDashboard8;
    private javax.swing.JButton btnLect8;
    private javax.swing.JButton btnLogout8;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSettings8;
    private javax.swing.JButton btnStudent8;
    public static javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDasboardTitle;
    private javax.swing.JLabel logo8;
    private javax.swing.JLayeredPane side8;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPw;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
