/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import static Admin.Admin_9ClassAssignment.txtclassID;
import Classes.Class;
import Classes.Lecturer;
import Classes.Module;
import Classes.ModuleLecturer;
import Login.AFS_LoginPage;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author aqilahazis
 */
public class Admin_8AssignClass extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_8AssignClass.class.getName());
    
    private String moduleID;
    private String lectID;

    /**
     * Creates new form Admin_8AssignClass
     */
    public Admin_8AssignClass() {
        initComponents();
        
        JTableHeader header = tblSchedule.getTableHeader();
        header.setPreferredSize(new Dimension(100, 30)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        side3 = new javax.swing.JLayeredPane();
        logo3 = new javax.swing.JLabel();
        btnDashboard3 = new javax.swing.JButton();
        btnStudent3 = new javax.swing.JButton();
        btnLect3 = new javax.swing.JButton();
        btnClass3 = new javax.swing.JButton();
        btnSettings3 = new javax.swing.JButton();
        btnLogout3 = new javax.swing.JButton();
        btnAcadlead3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDasboardTitle = new javax.swing.JLabel();
        cmbModule = new javax.swing.JComboBox<>();
        lblID = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        cmbLect = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        side3.setBackground(new java.awt.Color(24, 29, 49));
        side3.setOpaque(true);

        logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assessment-feedback-system-high-resolution-logo-transparent-3 (2).png"))); // NOI18N

        btnDashboard3.setBackground(new java.awt.Color(24, 29, 49));
        btnDashboard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logologlo.png"))); // NOI18N
        btnDashboard3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard3.setBorderPainted(false);
        btnDashboard3.setFocusPainted(false);
        btnDashboard3.setOpaque(true);
        btnDashboard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboard3ActionPerformed(evt);
            }
        });

        btnStudent3.setBackground(new java.awt.Color(24, 29, 49));
        btnStudent3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 2.png"))); // NOI18N
        btnStudent3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnStudent3.setOpaque(true);
        btnStudent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudent3ActionPerformed(evt);
            }
        });

        btnLect3.setBackground(new java.awt.Color(24, 29, 49));
        btnLect3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy.png"))); // NOI18N
        btnLect3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLect3.setOpaque(true);
        btnLect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLect3ActionPerformed(evt);
            }
        });

        btnClass3.setBackground(new java.awt.Color(24, 29, 49));
        btnClass3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/classesstings.png"))); // NOI18N
        btnClass3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClass3.setOpaque(true);
        btnClass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClass3ActionPerformed(evt);
            }
        });

        btnSettings3.setBackground(new java.awt.Color(24, 29, 49));
        btnSettings3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 5.png"))); // NOI18N
        btnSettings3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSettings3.setOpaque(true);
        btnSettings3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettings3ActionPerformed(evt);
            }
        });

        btnLogout3.setBackground(new java.awt.Color(24, 29, 49));
        btnLogout3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 6.png"))); // NOI18N
        btnLogout3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout3.setOpaque(true);
        btnLogout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout3ActionPerformed(evt);
            }
        });

        btnAcadlead3.setBackground(new java.awt.Color(24, 29, 49));
        btnAcadlead3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/please copy 3.png"))); // NOI18N
        btnAcadlead3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAcadlead3.setOpaque(true);
        btnAcadlead3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcadlead3ActionPerformed(evt);
            }
        });

        side3.setLayer(logo3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnDashboard3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnStudent3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnLect3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnClass3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnSettings3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnLogout3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        side3.setLayer(btnAcadlead3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout side3Layout = new javax.swing.GroupLayout(side3);
        side3.setLayout(side3Layout);
        side3Layout.setHorizontalGroup(
            side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side3Layout.createSequentialGroup()
                .addGroup(side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(side3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLect3)
                            .addComponent(btnLogout3)
                            .addComponent(btnSettings3)
                            .addComponent(btnAcadlead3)
                            .addComponent(btnStudent3)
                            .addGroup(side3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnClass3))))
                    .addGroup(side3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDashboard3)
                            .addComponent(logo3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        side3Layout.setVerticalGroup(
            side3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logo3)
                .addGap(39, 39, 39)
                .addComponent(btnDashboard3)
                .addGap(12, 12, 12)
                .addComponent(btnStudent3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLect3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcadlead3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClass3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSettings3)
                .addGap(55, 55, 55)
                .addComponent(btnLogout3)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side3)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(775, 643));

        lblDasboardTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblDasboardTitle.setText("Class Assignment");

        cmbModule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModuleActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblID.setText("Module:");

        lblID1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblID1.setText("Lecturer:");

        tblSchedule.setBackground(new java.awt.Color(204, 204, 204));
        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSchedule.setRowSelectionAllowed(false);
        tblSchedule.getTableHeader().setReorderingAllowed(false);
        tblSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblScheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSchedule);
        tblSchedule.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblSchedule.getColumnModel().getColumnCount() > 0) {
            tblSchedule.getColumnModel().getColumn(0).setResizable(false);
            tblSchedule.getColumnModel().getColumn(1).setResizable(false);
            tblSchedule.getColumnModel().getColumn(2).setResizable(false);
            tblSchedule.getColumnModel().getColumn(3).setResizable(false);
            tblSchedule.getColumnModel().getColumn(4).setResizable(false);
            tblSchedule.getColumnModel().getColumn(5).setResizable(false);
        }

        cmbLect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbLect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLectActionPerformed(evt);
            }
        });
        cmbLect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbLectKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblID)
                            .addComponent(lblID1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbModule, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbLect, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblDasboardTitle)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDasboardTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(cmbModule, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblID1))
                    .addComponent(cmbLect, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModuleActionPerformed
        String moduleID = (String) cmbModule.getSelectedItem();
        moduleID = moduleID.substring(0, moduleID.indexOf(' '));
        Lecturer.addLecttoCmb(cmbLect, moduleID);
    }//GEN-LAST:event_cmbModuleActionPerformed

    private void cmbLectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLectActionPerformed
        moduleID = (String) cmbModule.getSelectedItem();
        //moduleID = moduleID.substring(0, moduleID.indexOf(' '));

        lectID = (String) cmbLect.getSelectedItem();
        //lectID = lectID.substring(0, lectID.indexOf(' '));

        if (moduleID != null && lectID != null){
            moduleID = moduleID.substring(0, moduleID.indexOf(' '));
            String lectID = this.lectID.substring(0, this.lectID.indexOf(' '));

            String mlID = ModuleLecturer.searchMLID(moduleID, lectID);
            Class.classSchedule(mlID, tblSchedule);
        }
    }//GEN-LAST:event_cmbLectActionPerformed

    private void cmbLectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbLectKeyPressed
        //tblSchedule.setBackground(Color.white);
        //tblSchedule.setDefaultRenderer(Object.class, null);
        //tblSchedule.repaint(); 
//        
//        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
//            moduleID = (String) cmbModule.getSelectedItem();
//            //moduleID = moduleID.substring(0, moduleID.indexOf(' '));
//        
//            lectID = (String) cmbLect.getSelectedItem();
//            //lectID = lectID.substring(0, lectID.indexOf(' '));
//        
//            if (moduleID != null && lectID != null){
//                moduleID = moduleID.substring(0, moduleID.indexOf(' '));
//                lectID = lectID.substring(0, lectID.indexOf(' '));
//            
//                String mlID = ModuleLecturer.searchMLID(moduleID, lectID);
//                Class.classSchedule(mlID);
//            }
//        }
    }//GEN-LAST:event_cmbLectKeyPressed

    private void tblScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblScheduleMouseClicked
        int row = tblSchedule.rowAtPoint(evt.getPoint());
        int col = tblSchedule.columnAtPoint(evt.getPoint());
        
        Color color = getTableCellBackground.getTableCellBackground(tblSchedule, row, col);
        
        if(!color.equals(tblSchedule.getBackground())){
            JOptionPane.showMessageDialog(this, "Please select another time.", 
                                                "Information", 
                                                JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String day = tblSchedule.getColumnName(col);
            String startTime = tblSchedule.getValueAt(row, 0).toString();

            //panggil page 9
            new Admin_9ClassAssignment().setVisible(true);
            
            //System.out.println(lectID);
            Class.classAssignmentInIt(day, startTime, moduleID, lectID,
                    Admin_9ClassAssignment.txtLect,
                    Admin_9ClassAssignment.txtDay,
                    Admin_9ClassAssignment.txtStartTime);
            
            this.dispose();
        }
    }//GEN-LAST:event_tblScheduleMouseClicked

    private void btnStudent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudent3ActionPerformed
        //Assignment.Admin_2StudentMain.show();
        new Admin_2StudentMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudent3ActionPerformed

    private void btnLect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLect3ActionPerformed
        new Admin_5LecturerMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLect3ActionPerformed

    private void btnClass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClass3ActionPerformed

    }//GEN-LAST:event_btnClass3ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Class.initializeTblsched(tblSchedule);
        Module.addModuletoCmb(cmbModule);
        tblSchedule.getColumnModel().setColumnMargin(10);
    }//GEN-LAST:event_formComponentShown

    private void btnDashboard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard3ActionPerformed
        new Admin_1dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboard3ActionPerformed

    private void btnAcadlead3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcadlead3ActionPerformed
        new Admin_10AcadLeadMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcadlead3ActionPerformed

    private void btnSettings3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings3ActionPerformed
        new Admin_13Settings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSettings3ActionPerformed

    private void btnLogout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout3ActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
                "Logging out?", 
                "Confirmation", 
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new AFS_LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogout3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_8AssignClass().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcadlead3;
    private javax.swing.JButton btnClass3;
    private javax.swing.JButton btnDashboard3;
    private javax.swing.JButton btnLect3;
    private javax.swing.JButton btnLogout3;
    private javax.swing.JButton btnSettings3;
    private javax.swing.JButton btnStudent3;
    public static javax.swing.JComboBox<String> cmbLect;
    public static javax.swing.JComboBox<String> cmbModule;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDasboardTitle;
    public static javax.swing.JLabel lblID;
    public static javax.swing.JLabel lblID1;
    private javax.swing.JLabel logo3;
    private javax.swing.JLayeredPane side3;
    public static javax.swing.JTable tblSchedule;
    // End of variables declaration//GEN-END:variables
}
