package Lecturer;

import java.awt.Color;
import Classes.Lecturer;
import Classes.PasswordChangeResult;
import Login.AFS_LoginPage;
import javax.swing.JOptionPane;
//
public class LecturerProfile_ChangePassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LecturerProfile_ChangePassword.class.getName());
    private Lecturer lecturer;

    public LecturerProfile_ChangePassword(Lecturer lecturer) {
        initComponents();
        this.lecturer = lecturer;
        
        if (lecturer == null)
            return;
        
        UsernameTextField.setText(lecturer.getUsername());
        UsernameTextField.setBackground(new Color(252, 252, 252));
        UsernameTextField.setEditable(false);
    }

    // Show validation error
    private void showError(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this,
            msg,
            "Validation Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        H2ChangePassword = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JLayeredPane();
        Username = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        CurrentPass = new javax.swing.JLabel();
        CurrentPassTextField = new javax.swing.JTextField();
        NewPass = new javax.swing.JLabel();
        NewPassTextField = new javax.swing.JTextField();
        ConfirmNewPass = new javax.swing.JLabel();
        ConfirmNewPassTextField = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        ConfirmChangeButton = new javax.swing.JButton();
        TitleP6 = new javax.swing.JLabel();
        SidePanel2 = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        DashboardButton2 = new javax.swing.JButton();
        ClassButton2 = new javax.swing.JButton();
        AssessmentButton2 = new javax.swing.JButton();
        GradingButton2 = new javax.swing.JButton();
        ProfileButton2 = new javax.swing.JButton();
        AnalyticsButton2 = new javax.swing.JButton();
        LogoutButton2 = new javax.swing.JButton();
        ModuleButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(1031, 643));

        H2ChangePassword.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        H2ChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MPIconChangePassword.png"))); // NOI18N
        H2ChangePassword.setText("Change Password");
        H2ChangePassword.setToolTipText("");
        H2ChangePassword.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        H2ChangePassword.setIconTextGap(10);

        Username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Username.setText("Username");

        UsernameTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UsernameTextField.setText("jTextField1");
        UsernameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UsernameTextField.setOpaque(true);
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        CurrentPass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CurrentPass.setText("Current Password");

        CurrentPassTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CurrentPassTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentPassTextFieldActionPerformed(evt);
            }
        });

        NewPass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NewPass.setText("New Password");

        NewPassTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NewPassTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPassTextFieldActionPerformed(evt);
            }
        });

        ConfirmNewPass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ConfirmNewPass.setText("Confirm New Password");

        ConfirmNewPassTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ConfirmNewPassTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmNewPassTextFieldActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(229, 218, 235));
        CancelButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        CancelButton.setFocusPainted(false);
        CancelButton.setFocusable(false);
        CancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        CancelButton.setIconTextGap(-10);
        CancelButton.setOpaque(true);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ConfirmChangeButton.setBackground(new java.awt.Color(229, 218, 235));
        ConfirmChangeButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ConfirmChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MPButtonConfirm.png"))); // NOI18N
        ConfirmChangeButton.setText("Confirm Change");
        ConfirmChangeButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ConfirmChangeButton.setFocusPainted(false);
        ConfirmChangeButton.setFocusable(false);
        ConfirmChangeButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ConfirmChangeButton.setIconTextGap(-13);
        ConfirmChangeButton.setOpaque(true);
        ConfirmChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmChangeButtonActionPerformed(evt);
            }
        });

        ContentPanel.setLayer(Username, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(UsernameTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(CurrentPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(CurrentPassTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(NewPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(NewPassTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(ConfirmNewPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(ConfirmNewPassTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(CancelButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(ConfirmChangeButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConfirmChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrentPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmNewPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ConfirmNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CurrentPass, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CurrentPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmNewPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmNewPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        TitleP6.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        TitleP6.setText("My Profile");

        SidePanel2.setBackground(new java.awt.Color(24, 29, 49));
        SidePanel2.setToolTipText("");

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AFS Logo.png"))); // NOI18N

        DashboardButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DashboardButton2.setForeground(new java.awt.Color(248, 248, 248));
        DashboardButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconDb.png"))); // NOI18N
        DashboardButton2.setText("   Dashboard");
        DashboardButton2.setAlignmentY(0.0F);
        DashboardButton2.setBorder(null);
        DashboardButton2.setBorderPainted(false);
        DashboardButton2.setContentAreaFilled(false);
        DashboardButton2.setDefaultCapable(false);
        DashboardButton2.setFocusPainted(false);
        DashboardButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DashboardButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButton2ActionPerformed(evt);
            }
        });

        ClassButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ClassButton2.setForeground(new java.awt.Color(248, 248, 248));
        ClassButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconClass.png"))); // NOI18N
        ClassButton2.setText("   Class");
        ClassButton2.setToolTipText("");
        ClassButton2.setActionCommand("Class");
        ClassButton2.setAlignmentY(0.0F);
        ClassButton2.setBorder(null);
        ClassButton2.setBorderPainted(false);
        ClassButton2.setContentAreaFilled(false);
        ClassButton2.setDefaultCapable(false);
        ClassButton2.setFocusPainted(false);
        ClassButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ClassButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassButton2ActionPerformed(evt);
            }
        });

        AssessmentButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AssessmentButton2.setForeground(new java.awt.Color(248, 248, 248));
        AssessmentButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconAss.png"))); // NOI18N
        AssessmentButton2.setText("   Assessment");
        AssessmentButton2.setAlignmentY(0.0F);
        AssessmentButton2.setBorder(null);
        AssessmentButton2.setBorderPainted(false);
        AssessmentButton2.setContentAreaFilled(false);
        AssessmentButton2.setDefaultCapable(false);
        AssessmentButton2.setFocusPainted(false);
        AssessmentButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AssessmentButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssessmentButton2ActionPerformed(evt);
            }
        });

        GradingButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GradingButton2.setForeground(new java.awt.Color(248, 248, 248));
        GradingButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconGrading.png"))); // NOI18N
        GradingButton2.setText("    Grading");
        GradingButton2.setToolTipText("");
        GradingButton2.setAlignmentY(0.0F);
        GradingButton2.setBorder(null);
        GradingButton2.setBorderPainted(false);
        GradingButton2.setContentAreaFilled(false);
        GradingButton2.setDefaultCapable(false);
        GradingButton2.setFocusPainted(false);
        GradingButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GradingButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradingButton2ActionPerformed(evt);
            }
        });

        ProfileButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ProfileButton2.setForeground(new java.awt.Color(236, 217, 226));
        ProfileButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconProfileClick.png"))); // NOI18N
        ProfileButton2.setText("    Profile");
        ProfileButton2.setAlignmentY(0.0F);
        ProfileButton2.setBorder(null);
        ProfileButton2.setBorderPainted(false);
        ProfileButton2.setContentAreaFilled(false);
        ProfileButton2.setDefaultCapable(false);
        ProfileButton2.setFocusPainted(false);
        ProfileButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProfileButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButton2ActionPerformed(evt);
            }
        });

        AnalyticsButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AnalyticsButton2.setForeground(new java.awt.Color(248, 248, 248));
        AnalyticsButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconAnalytics.png"))); // NOI18N
        AnalyticsButton2.setText("    Analytics");
        AnalyticsButton2.setAlignmentY(0.0F);
        AnalyticsButton2.setBorder(null);
        AnalyticsButton2.setBorderPainted(false);
        AnalyticsButton2.setContentAreaFilled(false);
        AnalyticsButton2.setDefaultCapable(false);
        AnalyticsButton2.setFocusPainted(false);
        AnalyticsButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AnalyticsButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsButton2ActionPerformed(evt);
            }
        });

        LogoutButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LogoutButton2.setForeground(new java.awt.Color(248, 248, 248));
        LogoutButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconLogout.png"))); // NOI18N
        LogoutButton2.setText("    Logout");
        LogoutButton2.setAlignmentY(0.0F);
        LogoutButton2.setBorder(null);
        LogoutButton2.setBorderPainted(false);
        LogoutButton2.setContentAreaFilled(false);
        LogoutButton2.setDefaultCapable(false);
        LogoutButton2.setFocusPainted(false);
        LogoutButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogoutButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButton2ActionPerformed(evt);
            }
        });

        ModuleButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ModuleButton2.setForeground(new java.awt.Color(248, 248, 248));
        ModuleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconModule.png"))); // NOI18N
        ModuleButton2.setText("   Module");
        ModuleButton2.setAlignmentY(0.0F);
        ModuleButton2.setBorder(null);
        ModuleButton2.setBorderPainted(false);
        ModuleButton2.setContentAreaFilled(false);
        ModuleButton2.setDefaultCapable(false);
        ModuleButton2.setFocusPainted(false);
        ModuleButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ModuleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidePanel2Layout = new javax.swing.GroupLayout(SidePanel2);
        SidePanel2.setLayout(SidePanel2Layout);
        SidePanel2Layout.setHorizontalGroup(
            SidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(SidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanel2Layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(logo2)
                        .addGap(28, 28, 28))
                    .addGroup(SidePanel2Layout.createSequentialGroup()
                        .addGroup(SidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ClassButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DashboardButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ModuleButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(AssessmentButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProfileButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnalyticsButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(LogoutButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradingButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        SidePanel2Layout.setVerticalGroup(
            SidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(DashboardButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModuleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClassButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AssessmentButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GradingButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AnalyticsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProfileButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoutButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(SidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2ChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(TitleP6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(TitleP6)
                .addGap(18, 18, 18)
                .addComponent(H2ChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(SidePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void CurrentPassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentPassTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentPassTextFieldActionPerformed

    private void ConfirmNewPassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmNewPassTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmNewPassTextFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
            "No change.",
            "Cancel Update",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        new LecturerProfile(lecturer).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ConfirmChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmChangeButtonActionPerformed
        PasswordChangeResult result = lecturer.changePassword(
              CurrentPassTextField.getText().trim(),
              NewPassTextField.getText().trim(),
              ConfirmNewPassTextField.getText().trim()
          );

          switch (result) {
              case EMPTY_FIELDS ->
                  showError("All fields must be filled.");

              case WRONG_CURRENT_PASSWORD ->
                  showError("Current password is incorrect.");

              case SAME_AS_OLD ->
                  showError("New password cannot be the same as current password.");

              case CONFIRM_MISMATCH ->
                  showError("New password and confirmation do not match.");

              case WEAK_PASSWORD ->
                  showError("""
                      Weak password.
                      Password must contain:
                      - Uppercase letter
                      - Lowercase letter
                      - Number
                      - Special symbol (@$!%*?&)
                      """);

              case IO_ERROR ->
                  showError("Failed to update password. Please try again.");

              case SUCCESS -> {
                  javax.swing.JOptionPane.showMessageDialog(
                      this,
                      "Password updated successfully.",
                      "Success",
                      javax.swing.JOptionPane.INFORMATION_MESSAGE
                  );
                  new LecturerProfile(lecturer).setVisible(true);
                  this.dispose();
              }
          }
    }//GEN-LAST:event_ConfirmChangeButtonActionPerformed

    private void NewPassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPassTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPassTextFieldActionPerformed

    private void DashboardButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButton2ActionPerformed
        LecturerDashboard modulePage = new LecturerDashboard(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DashboardButton2ActionPerformed

    private void ClassButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassButton2ActionPerformed
        LecturerClass modulePage = new LecturerClass(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ClassButton2ActionPerformed

    private void AssessmentButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssessmentButton2ActionPerformed
        LecturerAssessment modulePage = new LecturerAssessment(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AssessmentButton2ActionPerformed

    private void GradingButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradingButton2ActionPerformed
        LecturerGrading modulePage = new LecturerGrading(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GradingButton2ActionPerformed

    private void ProfileButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButton2ActionPerformed
        LecturerProfile modulePage = new LecturerProfile(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProfileButton2ActionPerformed

    private void AnalyticsButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsButton2ActionPerformed
        LecturerAnalytics modulePage = new LecturerAnalytics(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AnalyticsButton2ActionPerformed

    private void LogoutButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButton2ActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
                "Logging out?", 
                "Confirmation", 
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new AFS_LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutButton2ActionPerformed

    private void ModuleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuleButton2ActionPerformed
        LecturerModule modulePage = new LecturerModule(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ModuleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyticsButton2;
    private javax.swing.JButton AssessmentButton2;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ClassButton2;
    private javax.swing.JButton ConfirmChangeButton;
    private javax.swing.JLabel ConfirmNewPass;
    private javax.swing.JTextField ConfirmNewPassTextField;
    private javax.swing.JLayeredPane ContentPanel;
    private javax.swing.JLabel CurrentPass;
    private javax.swing.JTextField CurrentPassTextField;
    private javax.swing.JButton DashboardButton2;
    private javax.swing.JButton GradingButton2;
    private javax.swing.JLabel H2ChangePassword;
    private javax.swing.JButton LogoutButton2;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ModuleButton2;
    private javax.swing.JLabel NewPass;
    private javax.swing.JTextField NewPassTextField;
    private javax.swing.JButton ProfileButton2;
    private javax.swing.JPanel SidePanel2;
    private javax.swing.JLabel TitleP6;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel logo2;
    // End of variables declaration//GEN-END:variables
}
