package Lecturer;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Classes.Lecturer;
import Classes.ProfileUpdateResult;
import Login.AFS_LoginPage;

public class LecturerProfile_UpdateProfile extends javax.swing.JFrame {
    private Lecturer lecturer;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LecturerProfile_UpdateProfile.class.getName());

    public LecturerProfile_UpdateProfile(Lecturer lecturer) {
        initComponents();
        this.lecturer = lecturer;
        
        TitleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[]{"", "Dr.", "Ts.", "Ts. Dr.", "Prof.", "Prof. Dr.", "Mr.", "Ms."}
        ));
        TitleComboBox.setBackground(new Color(255, 255, 255));

        loadProfileData();
        setReadOnly();
    }
    
    private void loadProfileData() {
        if (lecturer == null)
            return;

        LectIDTextField.setText(lecturer.getLecturerID());
        NameTextField.setText(lecturer.getName());
        EmailTextField.setText(lecturer.getEmail());
        PhoneNumberTextField.setText(lecturer.getPhoneNumber());
        AcadQualTextField.setText(lecturer.getAcademicQualification());
        AcadLeaderTextField.setText(lecturer.getAcadLeadID());
        UsernameTextField.setText(lecturer.getUsername());

        String title = lecturer.getTitle();
        if (title == null || title.equalsIgnoreCase("NULL")) {
            TitleComboBox.setSelectedIndex(0); // empty option
        } else {
            TitleComboBox.setSelectedItem(title);
        }
        
        AcadLeaderTextField.setText(
            lecturer.getAcademicLeaderName()
        );
    }
    
    
    // Read only. User not allowed to edit certain field.
    private void setReadOnly() {
        JTextField[] fields = {
            LectIDTextField, NameTextField, AcadLeaderTextField
        };

        for (JTextField f : fields) {
            f.setEditable(false);
            f.setBackground(new Color(252, 252, 252));
        }
    }

    private void showError(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this,
            msg,
            "Validation Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        DashboardButton2 = new javax.swing.JButton();
        ClassButton2 = new javax.swing.JButton();
        AssessmentButton2 = new javax.swing.JButton();
        GradingButton2 = new javax.swing.JButton();
        ProfileButton2 = new javax.swing.JButton();
        AnalyticsButton2 = new javax.swing.JButton();
        LogoutButton2 = new javax.swing.JButton();
        ModuleButton2 = new javax.swing.JButton();
        H2UpdateProfile = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JLayeredPane();
        LectID = new javax.swing.JLabel();
        LectIDTextField = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        TitleComboBox = new javax.swing.JComboBox<>();
        Email = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JLabel();
        PhoneNumberTextField = new javax.swing.JTextField();
        AcadLeader = new javax.swing.JLabel();
        AcadLeaderTextField = new javax.swing.JTextField();
        AcadQual = new javax.swing.JLabel();
        AcadQualTextField = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        ConfirmUpdateButton = new javax.swing.JButton();
        TitleP6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(1031, 643));

        SidePanel.setBackground(new java.awt.Color(24, 29, 49));
        SidePanel.setToolTipText("");

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AFS Logo.png"))); // NOI18N

        DashboardButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DashboardButton2.setForeground(new java.awt.Color(248, 248, 248));
        DashboardButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconDb.png"))); // NOI18N
        DashboardButton2.setText("   Dashboard");
        DashboardButton2.setAlignmentY(0.0F);
        DashboardButton2.setBorder(null);
        DashboardButton2.setBorderPainted(false);
        DashboardButton2.setContentAreaFilled(false);
        DashboardButton2.setDefaultCapable(false);
        DashboardButton2.setFocusPainted(false);
        DashboardButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DashboardButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButton2ActionPerformed(evt);
            }
        });

        ClassButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ClassButton2.setForeground(new java.awt.Color(248, 248, 248));
        ClassButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconClass.png"))); // NOI18N
        ClassButton2.setText("   Class");
        ClassButton2.setToolTipText("");
        ClassButton2.setActionCommand("Class");
        ClassButton2.setAlignmentY(0.0F);
        ClassButton2.setBorder(null);
        ClassButton2.setBorderPainted(false);
        ClassButton2.setContentAreaFilled(false);
        ClassButton2.setDefaultCapable(false);
        ClassButton2.setFocusPainted(false);
        ClassButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ClassButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassButton2ActionPerformed(evt);
            }
        });

        AssessmentButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AssessmentButton2.setForeground(new java.awt.Color(248, 248, 248));
        AssessmentButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconAss.png"))); // NOI18N
        AssessmentButton2.setText("   Assessment");
        AssessmentButton2.setAlignmentY(0.0F);
        AssessmentButton2.setBorder(null);
        AssessmentButton2.setBorderPainted(false);
        AssessmentButton2.setContentAreaFilled(false);
        AssessmentButton2.setDefaultCapable(false);
        AssessmentButton2.setFocusPainted(false);
        AssessmentButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AssessmentButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssessmentButton2ActionPerformed(evt);
            }
        });

        GradingButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GradingButton2.setForeground(new java.awt.Color(248, 248, 248));
        GradingButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconGrading.png"))); // NOI18N
        GradingButton2.setText("    Grading");
        GradingButton2.setToolTipText("");
        GradingButton2.setAlignmentY(0.0F);
        GradingButton2.setBorder(null);
        GradingButton2.setBorderPainted(false);
        GradingButton2.setContentAreaFilled(false);
        GradingButton2.setDefaultCapable(false);
        GradingButton2.setFocusPainted(false);
        GradingButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GradingButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradingButton2ActionPerformed(evt);
            }
        });

        ProfileButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ProfileButton2.setForeground(new java.awt.Color(236, 217, 226));
        ProfileButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconProfileClick.png"))); // NOI18N
        ProfileButton2.setText("    Profile");
        ProfileButton2.setAlignmentY(0.0F);
        ProfileButton2.setBorder(null);
        ProfileButton2.setBorderPainted(false);
        ProfileButton2.setContentAreaFilled(false);
        ProfileButton2.setDefaultCapable(false);
        ProfileButton2.setFocusPainted(false);
        ProfileButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProfileButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButton2ActionPerformed(evt);
            }
        });

        AnalyticsButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AnalyticsButton2.setForeground(new java.awt.Color(248, 248, 248));
        AnalyticsButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconAnalytics.png"))); // NOI18N
        AnalyticsButton2.setText("    Analytics");
        AnalyticsButton2.setAlignmentY(0.0F);
        AnalyticsButton2.setBorder(null);
        AnalyticsButton2.setBorderPainted(false);
        AnalyticsButton2.setContentAreaFilled(false);
        AnalyticsButton2.setDefaultCapable(false);
        AnalyticsButton2.setFocusPainted(false);
        AnalyticsButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AnalyticsButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsButton2ActionPerformed(evt);
            }
        });

        LogoutButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LogoutButton2.setForeground(new java.awt.Color(248, 248, 248));
        LogoutButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconLogout.png"))); // NOI18N
        LogoutButton2.setText("    Logout");
        LogoutButton2.setAlignmentY(0.0F);
        LogoutButton2.setBorder(null);
        LogoutButton2.setBorderPainted(false);
        LogoutButton2.setContentAreaFilled(false);
        LogoutButton2.setDefaultCapable(false);
        LogoutButton2.setFocusPainted(false);
        LogoutButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogoutButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButton2ActionPerformed(evt);
            }
        });

        ModuleButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ModuleButton2.setForeground(new java.awt.Color(248, 248, 248));
        ModuleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SideIconModule.png"))); // NOI18N
        ModuleButton2.setText("   Module");
        ModuleButton2.setAlignmentY(0.0F);
        ModuleButton2.setBorder(null);
        ModuleButton2.setBorderPainted(false);
        ModuleButton2.setContentAreaFilled(false);
        ModuleButton2.setDefaultCapable(false);
        ModuleButton2.setFocusPainted(false);
        ModuleButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ModuleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(logo2)
                        .addGap(28, 28, 28))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ClassButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DashboardButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ModuleButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(AssessmentButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProfileButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnalyticsButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(LogoutButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradingButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(DashboardButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModuleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClassButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AssessmentButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GradingButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AnalyticsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProfileButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoutButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        H2UpdateProfile.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        H2UpdateProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MPButtonUpdateProfile.png"))); // NOI18N
        H2UpdateProfile.setText("Update Profile");
        H2UpdateProfile.setToolTipText("");
        H2UpdateProfile.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        LectID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LectID.setText("Lecturer ID");

        LectIDTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LectIDTextField.setText("jTextField1");
        LectIDTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LectIDTextField.setOpaque(true);
        LectIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LectIDTextFieldActionPerformed(evt);
            }
        });

        Username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Username.setText("Username");

        UsernameTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UsernameTextField.setText("jTextField1");
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Name.setText("Name");

        NameTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NameTextField.setText("jTextField1");
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Title.setText("Title");

        TitleComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TitleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TitleComboBox.setFocusable(false);
        TitleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleComboBoxActionPerformed(evt);
            }
        });

        Email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Email.setText("Email");

        EmailTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailTextField.setText("jTextField1");
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        PhoneNumber.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhoneNumber.setText("Phone Number");

        PhoneNumberTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhoneNumberTextField.setText("jTextField1");
        PhoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTextFieldActionPerformed(evt);
            }
        });

        AcadLeader.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcadLeader.setText("Academic Leader");

        AcadLeaderTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcadLeaderTextField.setText("jTextField1");
        AcadLeaderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcadLeaderTextFieldActionPerformed(evt);
            }
        });

        AcadQual.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcadQual.setText("Academic Qualification");

        AcadQualTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcadQualTextField.setText("jTextField1");
        AcadQualTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcadQualTextFieldActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(229, 218, 235));
        CancelButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        CancelButton.setFocusPainted(false);
        CancelButton.setFocusable(false);
        CancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        CancelButton.setIconTextGap(-10);
        CancelButton.setOpaque(true);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ConfirmUpdateButton.setBackground(new java.awt.Color(229, 218, 235));
        ConfirmUpdateButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ConfirmUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MPButtonConfirm.png"))); // NOI18N
        ConfirmUpdateButton.setText("Confirm Update");
        ConfirmUpdateButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ConfirmUpdateButton.setFocusPainted(false);
        ConfirmUpdateButton.setFocusable(false);
        ConfirmUpdateButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ConfirmUpdateButton.setIconTextGap(-13);
        ConfirmUpdateButton.setOpaque(true);
        ConfirmUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmUpdateButtonActionPerformed(evt);
            }
        });

        ContentPanel.setLayer(LectID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(LectIDTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(Username, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(UsernameTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(Name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(NameTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(Title, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(TitleComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(Email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(EmailTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(PhoneNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(PhoneNumberTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(AcadLeader, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(AcadLeaderTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(AcadQual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(AcadQualTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(CancelButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ContentPanel.setLayer(ConfirmUpdateButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LectIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(LectID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ContentPanelLayout.createSequentialGroup()
                                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(262, 262, 262)
                                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(ContentPanelLayout.createSequentialGroup()
                                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(262, 262, 262)
                                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(AcadLeader, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(AcadLeaderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ContentPanelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(190, 190, 190))
                                    .addGroup(ContentPanelLayout.createSequentialGroup()
                                        .addComponent(TitleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ContentPanelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(AcadQual, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AcadQualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConfirmUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ContentPanelLayout.createSequentialGroup()
                                        .addComponent(LectID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LectIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ContentPanelLayout.createSequentialGroup()
                                        .addComponent(Email)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(Username)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addComponent(PhoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addComponent(AcadLeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AcadLeaderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AcadQual, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TitleComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(AcadQualTextField))
                .addGap(70, 70, 70)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        TitleP6.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        TitleP6.setText("My Profile");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2UpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(TitleP6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(TitleP6)
                .addGap(18, 18, 18)
                .addComponent(H2UpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void LectIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LectIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LectIDTextFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void PhoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextFieldActionPerformed

    private void AcadLeaderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcadLeaderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcadLeaderTextFieldActionPerformed

    private void AcadQualTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcadQualTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcadQualTextFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
            "No data changed.",
            "Cancel Update",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        new LecturerProfile(lecturer).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ConfirmUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmUpdateButtonActionPerformed
        ProfileUpdateResult result = lecturer.updateProfile(
            UsernameTextField.getText().trim(),
            NameTextField.getText().trim(),
            TitleComboBox.getSelectedItem().toString().isBlank() ? null
                : TitleComboBox.getSelectedItem().toString(),
            EmailTextField.getText().trim(),
            PhoneNumberTextField.getText().trim(),
            AcadQualTextField.getText().trim(),
            this
        );

        switch (result) {
            case SUCCESS -> {
                JOptionPane.showMessageDialog(this, "Profile updated successfully.");
                new LecturerProfile(lecturer).setVisible(true);
                dispose();
            }
            case EMPTY_FIELDS -> showError("All fields must be filled.");
            case INVALID_EMAIL -> showError("Invalid email address.");
            case INVALID_PHONE -> showError("Invalid phone number.");
            case USERNAME_EXISTS -> showError("Username already exists.");
            case PASSWORD_FAILED -> showError("Update cancelled due to failed authentication.");
            case IO_ERROR -> showError("Failed to save data.");
        }
        
        new LecturerProfile(lecturer).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConfirmUpdateButtonActionPerformed

    private void TitleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleComboBoxActionPerformed

    private void DashboardButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButton2ActionPerformed
        LecturerDashboard modulePage = new LecturerDashboard(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DashboardButton2ActionPerformed

    private void ClassButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassButton2ActionPerformed
        LecturerClass modulePage = new LecturerClass(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ClassButton2ActionPerformed

    private void AssessmentButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssessmentButton2ActionPerformed
        LecturerAssessment modulePage = new LecturerAssessment(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AssessmentButton2ActionPerformed

    private void GradingButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradingButton2ActionPerformed
        LecturerGrading modulePage = new LecturerGrading(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GradingButton2ActionPerformed

    private void ProfileButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButton2ActionPerformed
        LecturerProfile modulePage = new LecturerProfile(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProfileButton2ActionPerformed

    private void AnalyticsButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsButton2ActionPerformed
        LecturerAnalytics modulePage = new LecturerAnalytics(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AnalyticsButton2ActionPerformed

    private void LogoutButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButton2ActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
                "Logging out?", 
                "Confirmation", 
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new AFS_LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutButton2ActionPerformed

    private void ModuleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuleButton2ActionPerformed
        LecturerModule modulePage = new LecturerModule(lecturer);
        modulePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ModuleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcadLeader;
    private javax.swing.JTextField AcadLeaderTextField;
    private javax.swing.JLabel AcadQual;
    private javax.swing.JTextField AcadQualTextField;
    private javax.swing.JButton AnalyticsButton2;
    private javax.swing.JButton AssessmentButton2;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ClassButton2;
    private javax.swing.JButton ConfirmUpdateButton;
    private javax.swing.JLayeredPane ContentPanel;
    private javax.swing.JButton DashboardButton2;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JButton GradingButton2;
    private javax.swing.JLabel H2UpdateProfile;
    private javax.swing.JLabel LectID;
    private javax.swing.JTextField LectIDTextField;
    private javax.swing.JButton LogoutButton2;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ModuleButton2;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JButton ProfileButton2;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel Title;
    private javax.swing.JComboBox<String> TitleComboBox;
    private javax.swing.JLabel TitleP6;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel logo2;
    // End of variables declaration//GEN-END:variables
}
